joblib/test/test_numpy_pickle.py

AssertionError should be raised if the numpy pickle fail to raise a ValueError. Also the proper thing to check is the default pickle protocol rather than the python version.

Improve tests for python 2 and 3 compressed pickles compatibility

---

.travis.yml
README.rst
joblib/__init__.py

rather than python 3.2.
Any objections? One of the reason is that Python 3.2 has some idiosyncrasies (I recently realised than `u''` gives a SyntaxError and also python 3.2 is not available through conda which is very annoying to test fixes locally) and is probably not used that much in the wild.

Use python 3.3 in Travis test

---

joblib/__init__.py
setup.py
sphinx_pypi_upload.py

The only reference I could find that states that pythonhosted is the new official name is [here](http://www.mechanicalcat.net/richard/log/Python/Introducing_pythonhosted_org___the_new_packages_python_org)

Use pythonhosted.org rather than packages.python.org

---

joblib/hashing.py
joblib/pool.py
setup.py

since it is not supported anymore.
The only non completely trivial change is a tweak of the exception caught in hashing.py. With the recent addition of the bytes view in #204, I don't think that TypeError can be raised anymore.

Remove lingering python 3.2 specific code

---

joblib/_memory_helpers.py
joblib/func_inspect.py
joblib/memory.py
joblib/test/test_func_inspect.py
joblib/test/test_func_inspect_special_encoding.py

When caching a function's return value,  current implementation assume that the source file encoding of that function is the system's default encoding. If not, something bad happens.
This pull request added a source code encoding parameter to fix this problem. I think it would be useful.

Add source encoding parameter in Memory module

---

doc/memory.rst

In doc/memory.rst
> Warning
Because in the first run the array is a plain ndarray, and in the second run the array is a memmap, you can have side effects of using the Memory, especially when using mmap_mode=’r’ as the array is writable in the first run, and not the second. 
The problem in the warning has been fixed in #95 .
BTW, I am reading the official [manual](http://pythonhosted.org/joblib/memory.html#using-memmapping) to find this issue.

DOC: remove a invalid warning

---

joblib/parallel.py
joblib/test/test_parallel.py

Thanks for all the great work on joblib. When using it for parallel processing, some errors can cause a confusing stack that obscures the underlying issue:
```
File "python2.7/site-packages/joblib/parallel.py", line 651, in __call__
self.retrieve()
File "lib/python2.7/site-packages/joblib/parallel.py", line 534, in retrieve
raise exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)
```
TransportableExceptions take both the message and message type:
https://github.com/joblib/joblib/blob/001fab4ab42e604a5471a6bef9722ea3d77e4309/joblib/my_exceptions.py#L41
and this small change fixes the problem. Thanks again.

Correct number of arguments when raising TransportableException

---

joblib/test/__init__.py
joblib/test/test_disk.py
joblib/test/test_format_stack.py
joblib/test/test_func_inspect.py
joblib/test/test_hashing.py
joblib/test/test_logger.py
joblib/test/test_memory.py
joblib/test/test_my_exceptions.py
joblib/test/test_numpy_pickle.py
joblib/test/test_parallel.py
joblib/test/test_pool.py

as advised in the scikit-learn developers guide [here](http://scikit-learn.org/stable/developers/#coding-guidelines). For one this make it a lot easier to check that a test is failing on a released version of joblib but fixed in master.

Use absolute imports in tests

---

.travis.yml
continuous_integration/install.sh
joblib/test/data/create_numpy_pickle.py

to test that joblib has only a soft dependence on numpy. Note many doctests assume numpy is installed so doctests are disabled when WITHOUT_NUMPY="true".
I could not find a way to override the with-doctest value in setup.cfg (there doesn't seem to be a config flag saying --with-doctest=0 or a value of NOSE_WITH_DOCTEST which disables doctests) so I did it the hacky way:
```bash
cat setup.cfg | grep -v 'with-doctest=' > setup.cfg
```

Add Travis build config without numpy

---

CHANGES.rst
joblib/numpy_pickle.py
joblib/test/test_numpy_pickle.py

Here is the kind of error message that users get when trying to load an object that has both memmap-able arrays and object-dtyped arrays in ther internal data-structures:
```
======================================================================
ERROR: joblib.test.test_numpy_pickle.test_memmap_persistence_mixed_dtypes
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/ogrisel/venvs/py34/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
self.test(*self.arg)
File "/Users/ogrisel/code/joblib/joblib/test/test_numpy_pickle.py", line 225, in test_memmap_persistence_mixed_dtypes
a_clone, b_clone = numpy_pickle.load(filename, mmap_mode='r')
File "/Users/ogrisel/code/joblib/joblib/numpy_pickle.py", line 520, in load …
```

[MRG] mmap_mode for mixed dtype objects

---

joblib/numpy_pickle.py
joblib/test/test_numpy_pickle.py

If installed, numpy >= 1.3 is required according to the README.rst.
I double-checked that the `memmap_mode` argument was indeed introduced in numpy 1.3.

[MRG] Remove code specific to numpy < 1.3

---

CHANGES.rst
doc/parallel.rst
joblib/parallel.py
joblib/test/test_parallel.py

Let's enable the forkserver start method by default under Python 3.4+

[MRG] FIX make joblib not break BLAS / OpenMP under Python 3.4+

---

joblib/test/test_numpy_pickle.py

Quick fix to have tests pass under Python 3.5 and later. Will merge if travis is green.

[MRG] FIX make pickle test pass with Python 3.5

---

joblib/_compat.py
joblib/hashing.py
joblib/test/test_hashing.py

Shoulf fix bug #231, maybe #213 and nilearn/nilearn#771

[MRG+1] Made hashing module robust to dtype and string shared in memory

---

.travis.yml
continuous_integration/install.sh

In the future this will enable us to test all supported numpy versions
rather than only 1.9 which is the one that the default Travis
environment contains.
Note: this is taken mostly from the nilearn Travis continuous_integration/install.sh.

Switch to conda environments for Travis

---

.travis.yml
joblib/test/test_memory.py
joblib/test/test_parallel.py

Fix #244 and add python 3.5 to Travis. 
The fixes were done in the simplest way possible.
In particular, the deprecation warnings coming from inspect.getargspec will be fixed in a separate PR.

[MRG] Add python3.5 to Travis

---

README.rst

This is the numpy version in Ubuntu 12.04 LTS and is consistent with the scikit-learn requirement.

[MRG] Bump up required numpy version to 1.6.1

---

CHANGES.rst
joblib/hashing.py
joblib/test/test_hashing.py

Should prevent having the same hash for a given object under Python 2 and Python 3.

[MRG+1] Use default pickle protocol for hashing

---

joblib/format_stack.py
joblib/test/test_format_stack.py

This update should address issue https://github.com/joblib/joblib/issues/258.

Prevent tokenizing .pyc files in format_records

---

joblib/my_exceptions.py
joblib/parallel.py
joblib/test/test_my_exceptions.py
joblib/test/test_parallel.py

Supersedes #261.
Raising custom exceptions in worker processes with a non trivial `__init__` (it need to take positional arguments)
```python
from joblib.parallel import Parallel, delayed
class MyExceptionWithFinickyInit(Exception):
"""An exception class with non trivial __init__
"""
def __init__(self, a, b, c, d):
self.a, self.b, self.c, self.d = a, b, c, d
def exception_raiser(x):
if x == 7:
raise MyExceptionWithFinickyInit('a', 'b', 'c', 'd')
return x
def test_capture_exception():
print('result: ', Parallel(n_jobs=2)(
delayed(exception_raiser)(i) for i in range(10)))
if __name__ == '__main__':
test_capture_exception()
```
Output:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call …
```

[MRG] Make joblib.Parallel more robust to custom exceptions

---

joblib/format_stack.py

The string `sys.version` should not be used for version checks (as it may or may not contain the version number at the beginning) so this change updates it to be done using `sys.version_info`. See also the note in the documentation: https://docs.python.org/3/library/sys.html#sys.version.

[MRG+1] Avoid use of sys.version for version checks

---

joblib/test/test_parallel.py
joblib/test/test_testing.py
joblib/testing.py

This functionality was broken when we changed the default process start method for 3.4+ to be forksever as mentioned in https://github.com/joblib/joblib/issues/263.
Now at least there is a test for it.

[MRG+1] Add test for Parallel with interactively defined function

---

joblib/parallel.py

This is a fix for a deadlock identified in #295.

[MRG] deadlock between async dispatch and exception handling

---

CHANGES.rst
joblib/hashing.py
joblib/test/test_hashing.py

FIX: fixing hashing with mixed dtype + test

---

CHANGES.rst
joblib/my_exceptions.py
joblib/test/test_my_exceptions.py

Fix #269.
Note that if the exception raised in a worker process is not inheritable, the exception raised in the master process will be JobException.

[MRG+1] Fix my_exceptions._mk_exception when input exception is not inheritable

---

CHANGES.rst
joblib/parallel.py
joblib/pool.py
joblib/test/common.py
joblib/test/test_parallel.py
joblib/test/test_pool.py

The automatic memmap feature of joblib can be mislead by the reuse of `id()` values for recently garbage collected numpy arrays as demonstrated in the non-regression test of this PR. This problem is actually quite frequent when generating large numpy arrays with a Python generator.
This PR fixes the issues by systematically hashing the arrays to find a robust unique identifier for the filenames of the temporary memmap'ed arrays.
I ran the benchmark script varying the parameters and could not find a configuration where hashing could cause a very large performance degradation w.r.t. the current master.
This fixes scikit-learn/scikit-learn#6063.

[MRG] Fix auto memmap gc failure

---

joblib/hashing.py
joblib/test/test_hashing.py

Should fix #308 
This just applied the solution proposed in the warning message. Maybe there are other solutions.
I tested this with the following snippet and the warning seems to be gone (try with numpy 1.10.2):
```python
import warnings, joblib
import numpy as np
a = np.ones((10,10,10,10), order='F')
with warnings.catch_warnings(record=True) as w:
warnings.simplefilter("always")
joblib.hash(a)
print(len(w))
if len(w):
print(str(w[-1].message))
```

[MRG] fix deprecation warning in hashing.py

---

CHANGES.rst
joblib/numpy_pickle.py
joblib/test/test_numpy_pickle.py

[MRG+1] Allow passing Path objects to joblib.{dump,load}.

---

joblib/parallel.py

Typo, "with the with the" → "with the" on [this page](https://pythonhosted.org/joblib/parallel.html#joblib.Parallel) in the documentation.

Typo, "with the with the" → "with the" in doc

---

doc/parallel.rst
joblib/_parallel_backends.py
joblib/parallel.py
joblib/test/test_parallel.py

This addresses @mrocklin's feature request in #322. It builds on top of #321.

[MRG] Parallel backend parameters

---

doc/parallel.rst
joblib/parallel.py
joblib/test/test_parallel.py

This is a refinement for the new `parallel_backend` context manager introduced in #306.
This makes it possible to override the default value of `n_jobs` used internally by library code using the context manager.
Note in particular that `parallel_backend` uses `n_jobs=-1` by default meaning to use all the available workers of my registered backend. For instance the following will use all the `ipyparallel` backend and by default will use all the available worker without having the change all my code to pass `n_jobs=-1` everywhere. This is particularly useful when doing nested cross-validation of scikit-learn models, for instance by calling `cross_val_score` and `GridSearchCV` within one another:
```python
with parallel_backend('ipyparallel'):
call_my_nested_cross_vall_parameter_search()
``` …

[MRG] make it possible to pass n_jobs to parallel_backend context

---

joblib/parallel.py

This should fix #327 and only consists to skip erroneous reporting if remaining time is negative.

FIX skip status display if remaining time is negative

---

CHANGES.rst
joblib/pool.py

FIX '[Error 5] Access is denied' under Windows

---

joblib/disk.py
joblib/parallel.py
joblib/test/test_disk.py

The only usage I could find was actually converting in bytes by doing `1024 * memstr_to_kbytes`.
Any objections?
Full disclosure I am using memstr_to_(k)bytes in the lru-cache PR which is why I bumped into this.

[MRG+1] Replace memstr_to_kbytes by memstr_to_bytes that return size in bytes

---

.travis.yml
joblib/test/test_numpy_pickle.py

The idea behind this test is to verify that pickle compressed with BinaryZlibFile object uses a valid `gzip` and `zlib` format. So the compressed pickle files can be uncompressed using regular command line tools and reloaded using `joblib.load`

TST: add test that checks compression files generated by joblib.dump

---

joblib/_parallel_backends.py
joblib/parallel.py
joblib/test/test_parallel.py

This adds an explicit way to cancel submitted tasks when an exception is raised. This is useful to clean up the queues of some backends such as distributed.
It also simplifies the handling of exceptions in general.

Explicit handling of job cancellation on first collected exception

---

README.rst
doc/installing.rst

Update installation procedure in the documentation. I think everyone now uses `pip` or `conda`. Fix #339.

DOC: update joblib installation procedure in the documentation

---

joblib/numpy_pickle.py
joblib/test/test_numpy_pickle.py

Should fix #362.
With pickle protocol 4, the Pickler uses a framer member object to avoid committing bytes too often. With the joblib hack, which consists in writing a numpy wrapper object __before__ the array buffer (see [here](https://github.com/joblib/joblib/blob/master/joblib/numpy_pickle.py#L266)), the new framer was delaying the actual write of the wrapper after the array buffer is written in the file.
The fix consists in forcing the commit of bytes using the framer member of the pickler. A non regression test is there as well.

FIX: persistence with pickle HIGHEST_PROTOCOL

---

continuous_integration/flake8_diff.sh
setup.cfg

Improvements:
* on a PR it runs on the PR branch rather than on the result of
the merge.
* runs fine in a branch configured to be trigger a Travis build
* better mechanism for finding the REMOTE to diff against
* it shows the source together with the PEP8 violation
Also ignoring `joblib/__init__.py` in setup.cfg is not necessary anymore since we are not showing any context.

[MRG+1] Improve flake8_diff.sh

---

CHANGES.rst
doc/persistence.rst
doc/persistence_fixture.py
joblib/numpy_pickle.py
joblib/numpy_pickle_utils.py
joblib/test/test_numpy_pickle.py

This PR should fix #341 and fix #312.
Examples of new usage:
```python
import joblib
data = "some data to persist"
with open('/tmp/test.pkl', 'wb') as f:
joblib.dump(data, f)
with open('/tmp/test.pkl', 'rb') as f:
print(joblib.load(f))
import gzip
with gzip.GzipFile('/tmp/test.pkl.gz', 'wb') as f:
joblib.dump(data, f)
with gzip.GzipFile('/tmp/test.pkl.gz', 'rb') as f:
print(joblib.load(f))
with open('/tmp/test.pkl.gz', 'rb') as f:
print(joblib.load(f))
import io
buf = io.BytesIO()
joblib.dump(data, buf)
joblib.load(buf)
```
Test functions are still missing.

[MRG]  persistence in/from file objects

---

CHANGES.rst
joblib/format_stack.py
joblib/test/test_format_stack.py

Fixes #101.
Took the fix from IPython.core.ultratb.py

[MRG+1] Fix format_stack with compiled code (e.g. .so or .pyd) in the traceback

---

CHANGES.rst
joblib/numpy_pickle_utils.py
joblib/test/test_numpy_pickle_utils.py

Hi everyone,
It seems that BinaryZlibFile cannot handle unicode filenames in python2. I just added the unicode type to check, but it's not python3 compliant now I guess .. Does it need to be ? Is there a workaround otherwise to make it works for both py2 and py3 ?

[numpy_pick_utils] BinaryZlibFile couldn't handle unicode filenames.

---

continuous_integration/install.sh
continuous_integration/test_script.sh

flake8 tries to checkout the branch before merge and the checkout was
failing because of the setup.cfg modifications.
The error showed up for the first time in #357.
I'll merge this one if Travis is green.

[MRG] Only override setup.cfg when running the tests

---

CHANGES.rst
joblib/memory.py
joblib/test/test_memory.py

While working on a cache memory refactoring, I noticed that some DeprecationWarning were there since a long time (commit 59adb5e9 is present starting from version 0.8.0).
This PS is just meant to let people know of a future removal.

MAINT: give version information in memory deprecation warning

---

CHANGES.rst
joblib/memory.py
joblib/test/test_memory.py

This is the first step in having a cache replacement policy in joblib whose main goal is to avoid cache folders to grow and eventually fill the disk. See the [initial issue](https://github.com/joblib/joblib/issues/85) with additional details.
Still need to be done:
Caveats or more controversial things on the todo list:

[MRG] LRU cache replacement

---

joblib/test/test_format_stack.py

on Debian systems it is mtrand.x86_64-linux-gnu.so since arch is x86_64

BF: allow for _ in the filename for mtrand.so

---

joblib/_parallel_backends.py
joblib/test/test_parallel.py
joblib/test/test_testing.py
joblib/testing.py

suppress a warning if a daemonic process creates parallel jobs with n_jobs=1
#405

[MRG+1] Remove warnings in nested Parallel when the inner Parallel has n_jobs=1

---

.travis.yml
continuous_integration/test_script.sh
joblib/_parallel_backends.py
joblib/test/test_parallel.py

From https://github.com/joblib/joblib/issues/391#issuecomment-250953533:
> I am observing first issue (AttributeError: 'NoneType' object has no attribute 'current_process') also while building fresh sklearn against the fresh joblib 0.10.2. To not starve build hosts I set JOBLIB_MULTIPROCESSING=0 which is just supposed to turn joblib multiprocessing off, while still performing the execution (worked e.g. with joblib 0.9.4 and before). Unfortunately logic in 0.10.2 seems to be flawed since if 0 it sets mp to None, but then without check tries to access its attributes.
> I guess it would be nice if there also was a test which would set this variable to 0 and attempts perform computation(s).

[MRG+1] Fix tests when multiprocessing is disabled

---

joblib/numpy_pickle.py
joblib/numpy_pickle_utils.py
joblib/test/test_numpy_pickle.py

This is a small optimization. Maybe we could check if the passed fileobj is seekable before detecting the compressor and raise an error if it's not the case.
Related to #398.

[MRG] simplify loading of compressed files

---

joblib/test/test_numpy_pickle.py

Thanks to @ogrisel suggestion, here is a piece of code showing how to use joblib pickle functions with python sockets.
Unfortunately, this is only Python3 compatible : python 2 socket file doesn't support seek and peek functions.

[MRG] add a test showing how to pickle in socket

---

CHANGES.rst
joblib/_parallel_backends.py
joblib/test/test_parallel.py

This is to address the following comment:
https://github.com/joblib/joblib/issues/180#issuecomment-253266247

[MRG+1] make multiprocessing backend robust to main thread name

---

joblib/parallel.py
joblib/test/test_parallel.py

Other exceptions should be raised rather than triggering the alternative
import.

Catch only ImportErrors

---

doc/parallel_numpy_fixture.py
doc/persistence_fixture.py
joblib/test/common.py
joblib/test/test_disk.py
joblib/test/test_format_stack.py
joblib/test/test_func_inspect.py
joblib/test/test_hashing.py
joblib/test/test_memory.py
joblib/test/test_my_exceptions.py
joblib/test/test_numpy_pickle.py
joblib/test/test_numpy_pickle_compat.py
joblib/test/test_parallel.py
joblib/test/test_pool.py
joblib/test/test_testing.py
joblib/testing.py

To initiate the migration form nose to py.test, this PR first of all removes all the direct usages of "nose" in all test scripts. It wraps the following utilities of **nose / unittest** modules in **joblib/testing.py**
- `assert_true`, `assert_false`
- `assert_equal`, `assert_not_equal`
- `assert_raises`
- `with_setup`, `SkipTest`
```python
from nose.tools import assert_equal
from nose import with_setup
import nose
nose.SkipTest()
nose.tools.assert_raises(*args, **kwargs)
```
have been replaced in a uniform fashion:
```python
from joblib.testing import (assert_equal, assert_raises,
SkipTest, with_setup) # preserve pep8 length
SkipTest()
assert_raises(*args, **kwargs)
```
- No unused imports from `joblib.testing`
- Everything from `joblib.testing` is imported as `from x import y, z`
This …

[MRG+1] Remove all nose imports from test scripts.

---

joblib/test/test_disk.py
joblib/test/test_format_stack.py
joblib/test/test_func_inspect.py
joblib/test/test_hashing.py
joblib/test/test_memory.py
joblib/test/test_my_exceptions.py
joblib/test/test_numpy_pickle.py
joblib/test/test_numpy_pickle_compat.py
joblib/test/test_parallel.py
joblib/test/test_pool.py

Native Python ships `exceptions` module which has an implementation of `AssertionError`. This exception is raised when any statement using `assert` keyword is incorrect. When the tests are run with `py.test`, this is overriden by `_pytest.assertion.reinterpret.AssertionError`.  
Hence instead of using `assert_true`, `assert_false`, `assert_equal ` and `assert_not_equal` methods, using `assert` keyword statements provides a helpful error log for debugging upon failing tests using `py.test` command.  
Besides this, the replacement can be welcoming because:
```python
assert_true(a == b)
assert_equal(a, b)
assert_false(a != b)
assert a == b 
```
Execution with py.test causes three tests to fail, which will be taken up just after this PR.

[MRG] Replace assert_* methods with "assert" keyword statements.

---

continuous_integration/flake8_diff.sh

instead of finding the common ancestor with git merge-base. As per the
git diff documentation:
"git diff A...B" is equivalent to "git diff $(git-merge-base A B) B"

[MRG] Use commit range for diff in flake8_diff.sh

---

CHANGES.rst
README.rst
joblib/pool.py
joblib/testing.py
setup.py

follow up of #437.
For the record, there were remaining occurrences of python 2.6:
```
README.rst:versions are 2.6+ and 3.3+). Numpy (at least version 1.6.1) is an
joblib/func_inspect.py:    once we drop support for Python 2.6. We went for a simpler
joblib/func_inspect.py:    which is not available in Python 2.6.
joblib/numpy_pickle_utils.py:    Required as e.g. ZipExtFile in python 2.6 can return less data than
joblib/pool.py:    # customize the dispatch table without side effects in Python 2.6
joblib/testing.py:    # Python <= 2.6, we still need nose here
setup.py:              'Programming Language :: Python :: 2.6',
```
2 side notes:
* the `func_inspect.py` change should deserve a dedicated PR (see [comment](https://github.com/joblib/joblib/pull/437#issuecomment-264476963) )
* the …

Remove py26 bis

---

appveyor/requirements.txt
continuous_integration/install.sh
doc/sphinxext/numpydoc/numpydoc.py
joblib/test/common.py
joblib/test/test_hashing.py
joblib/testing.py

With this PR **joblib** finally drops `nose` as its own dependency.
```shell
kd@dragonstone:~/Documents/joblib$ git grep nose
CHANGES.rst:    py.test is used to run the tests instead of nosetests.
CHANGES.rst:    ``python setup.py test`` or ``python setup.py nosetests`` do not work
```
_NOTE_: I have changed the mechanism of conditional setup of tests (based on availability of multiprocessing / shared memory) in **test_hashing.py** - that is, through a fixture mechanism. It is the "pytest design technique" and although one needs to specify same argument (as I have specified `tmpdir_path`) to many tests, looking at a specific method signature one can easily know that this test "requires" something prior its execution...
* Similar thing can be exercised in other modules, but for this PR …

[MRG] Remove nose dependency completely from project.

---

joblib/test/common.py
joblib/test/test_func_inspect.py
joblib/test/test_hashing.py

This PR deals with refactor of tests in **test_func_inspect.py** to adopt the pytest flavor.
* Prior to this PR, each method had several `yield` based statements where the test cases comprised of a set of functions with args and kwargs as well. I have proposed a `fixture` which returns a dictionary of functions to make `parametrization` easier.
* `with_numpy` decorator is now a `pytest.skipif` marker [Commented for now, will be uncommented after **test_hashing.py** is pytestified. Because this skipif marker does not work well with `yield` based tests.]
* The function names `g` and `f2` have been interchanged. Earlier `g` was decorated with `@mem.cache` earlier, and it was the only one function. All other functions - `f`, `f2`, `h`, `i`, `j`, `k` were normal undecorated ones. This name …

[MRG] Refactor test_func_inspect.py as per pytest design.

---

joblib/test/test_logger.py

This PR deals with refactor of tests in **test_logger.py** to adopt the pytest flavor.
There is one only test method, which used a temporary file to log output. The setup and teardown for the same, using `tempfile` module has been removed, and instead, pytest's own `tmpdir` fixture is specified as function parameter.
Instead of raising an AssertionError based on condition, direct usage of `assert` keyword is used.

[MRG] Refactor test_logger.py as per pytest design.

---

joblib/test/test_hashing.py

This PR deals with refactor of tests in **test_hashing.py** to adopt the pytest flavor.
* Parametrization of certain tests have been done by an accompanying fixture to protect numpy specific code using `@with_numpy`. Refer https://github.com/joblib/joblib/issues/411#issuecomment-266444495 for more details.
* Regex checking of tests has been done using pytest now.
* `tmpdir_path` fixture has been removed and pytest's own `tmpdir` is brought back to used to keep uniformity across modules. Some older occurences (if any) will be taken care later.
* Some cosmetic changes like reordering of imports has been included.

[MRG] Refactor test_hashing.py as per pytest design.

---

joblib/test/test_logger.py
joblib/test/test_memory.py
joblib/test/test_parallel.py

Since joblib now uses pytest instead of nose, one does not need to explicitly capture the output. In many tests, `sys.stdout` and `sys.stderr` were temporarily replaced by a dummy `StringIO` or `tempfile`, which were restored back after test execution completed.
This manual switching is now removed owing to default behaviour of pytest (refer #457 description). Pytest's `capsys` fixture is used to grab the output and perform regex matching.

[MRG] Replace stdout / stderr switching in smoke tests with capsys.

---

joblib/test/test_memory.py
joblib/test/test_numpy_pickle.py
joblib/test/test_parallel.py
joblib/testing.py
setup.cfg

This PR targets on completely removing all the pytest warnings existing in all the tests at this stage. On `master`, at the base of this PR, there are **189** pytest warnings - mostly because pytest >= 3 has deprecated support of `yield` based tests. 
* Statements `yield`ing a simple function (callable) have been removed and a normal function call is included there.
* Statements `yield`ing `assert_*` methods have been replaced with simple `assert` keywords as of now.
* Finally `--disable-pytest-warnings` has been removed.
The goal of this PR is to eliminate all pytest warnings existing already.

[MRG] Remove pytest warnings due to yield based tests.

---

joblib/test/test_parallel.py

* `test_nested_parallel_warnings` method of **test_parallel.py** has been refactored to use pytest's `capfd` fixture instead of `check_subprocess_call` helper function.
* Warnings happening in child processes were not consistent on Travis CI python 3 job. So we access the captured output of a test function to check for warnings directly in test method.
* Reference: http://doc.pytest.org/en/latest/capture.html#accessing-captured-output-from-a-test-function
* Since the warnings are raises in child processes, `pytest.warns` as well as `capsys` fixture cannot be used, as per the explanation in reference above.

Fix uncertain failures of test_nested_parallel_warnings.

---

joblib/format_stack.py
joblib/test/test_format_stack.py

Fix #420.
I don't really understand why the padding was not consistent in multiple places but removing it fixes it. Any reason why the padding was added @GaelVaroquaux? All in all this is a bit of a edge case, because it only happens when the source has less than 10 lines.

[MRG] Fix wrong line being pointed at in subprocess exception

---

joblib/test/test_memory.py
joblib/test/test_numpy_pickle.py
joblib/test/test_numpy_pickle_compat.py
joblib/test/test_numpy_pickle_utils.py
joblib/test/test_pool.py

Several modules declare a setup and teardown where a temporary directory was created and its path was set as a global variable. Creation and deletion of this directory was handled manually while setup and teardown. This has been replaced by pytest's `tmpdir` fixture.
It is a `py.path.local` object, and has to be specified as a parameter in tests requiring a temporary directory.

[MRG] Replace manual setup / teardown of temp directory with 'tmpdir' fixture.

---

joblib/test/test_testing.py

This PR deals with refactor of tests in **test_testing.py** to adopt the pytest flavor.
Regex checking of exception messages is carried out by `pytest_assert_raises`.

[MRG] Refactor test_testing.py as per pytest design.

---

joblib/test/test_disk.py
joblib/test/test_func_inspect.py
joblib/test/test_hashing.py
joblib/test/test_memory.py
joblib/test/test_numpy_pickle.py
joblib/test/test_parallel.py
joblib/test/test_pool.py
joblib/test/test_testing.py
joblib/testing.py

`pytest.raises` produces a less noisy error log upon failure. This PR replaces all the `assert_raises` and `assert_raises_regex` calls with `pytest_assert_raises`. Finally the `unittest` 's `assert_raises` is removed from `joblib.testing` and `pytest_assert_raises` has been renamed as `raises`.
* `assert_raises` and `assert_raises_regex` calls have been modified as:
```python
with raises(ExceptionName) as excinfo:   # pytest.raises
code_that_raises_exception()
excinfo.match('exception message regex')
```
* `assert_raises` (old) and `assert_raises_regex` were the last of helpers used from `unittest` module. By this PR, the testing infrastructure no longer directly depends on `unittest`.

[MRG] Use pytest for asserting exceptions in all test methods.

---

CHANGES.rst
joblib/parallel.py
joblib/test/test_parallel.py

[MRG] Allow backend instance in Parallel constructor

---

joblib/test/test_memory.py
joblib/test/test_numpy_pickle.py
joblib/test/test_parallel.py
joblib/testing.py

This PR uses `with pytest.warns` blocks (initially planned `recwarn` fixture of pytest) to record raised warnings in a particular test and assert warning messages, instead of `with warning.catch_warnings` blocks.

[MRG] Use 'with pytest.warns' blocks to assert warnings.

---

.gitignore

When a test failed, py.test generates a .cache folder. This add it to .gitignore.

MAINT: ignore .cache directory generated by py.test when a test failed

---

joblib/test/test_disk.py
joblib/test/test_func_inspect.py
joblib/test/test_hashing.py
joblib/test/test_numpy_pickle.py
joblib/test/test_numpy_pickle_utils.py

This PR parametrizes tests from **test_numpy_pickle.py** and **test_numpy_pickle_utils.py**. Also, cosmetic changes in `@parametrization` decorators of **test_disk.py** and **test_func_inspect.py** have been included.

[MRG] Perform parametrization on numpy pickle tests.

---

joblib/test/test_memory.py

This PR deals with refactor of tests in **test_memory.py** to adopt the pytest flavor.
* Create two new fixtures `memory` and `no_memoize_memory` as they are used by almost all of the tests.
* Remove memory clearing calls at certain places, because earlier temporary directory was created / destroyed manually. Now pytest's tmpdir already ensures isolation with other tests.
* Parametrize tests wherever it seems straightforward.

[MRG] Refactor test_memory.py as per pytest design.

---

.travis.yml

Maybe it is be the reason we lost coverage report after #472 was merged. cc @aabadie.

[MRG] Add missing quote in .travis.yml

---

joblib/test/test_parallel.py

A set of tests have been parametrized in a simple fashion. Certain tests used `try - final` blocks to register new backend and remove it later. But the test may misbehave if `register_parallel_backend` itself is broken. Also, there's a test for `register_parallel_backend` where this method itself is tested, while in some other tests, it is just a part of test setup.
Temporary changes like this (commonly known as **monkeypatching**) are undertaken through pytest's standard `monkeypatch` fixture. using it clearly states that the line written in test is just a part of setup for that particular test.

[MRG] Perform parametrization on certain tests of test_parallel.py

---

joblib/pool.py

You could get "TypeError: catching classes that do not inherit from
BaseException is not allowed" when hitting Control-C.

[MRG] WindowsError should be a type under non-Windows platforms

---

appveyor.yml
appveyor/install.ps1
appveyor/requirements.txt

Also use the wheels on PyPI rather than on rackspace.

[MRG] Use Python 3.5 on AppVeyor

---

continuous_integration/appveyor/test.ps1
joblib/test/test_disk.py
joblib/test/test_memory.py

As noted in https://github.com/joblib/joblib/pull/503#issuecomment-283429775, the exit code of the test script is not correct. This results in a successful build even if there were pytest errors.

[MRG] Fix AppVeyor test exit code

---

Makefile
joblib/pool.py
joblib/test/test_pool.py

This PR addresses issue #510 and moves the code used to compute the path to the `temp_folder` from `joblib.pool.MemmapingPool` to a separate private function, so that it could be potentially (carefully) reused with `joblib.Memory`.

Move temp_dir path generation to a separate private function

---

continuous_integration/travis/install.sh

Turns out Miniconda-latest is actually a semi-old miniconda2 installer ...
I'll merge this one if the CIs are green.

[MRG+1] MAINT use latest miniconda3 installer

---

setup.cfg

The new release of pytest adds a plugin to capture all warnings and
output them at the end. This was causing a test failure, as we were
checking that a warning was raised in an external process by checking
the captured stderr. Since the warning is raised in an external process
we can't use `pytest.warns`, and none of the current pytest-warnings
configuration settings allow turning off capturing in a way that works
for this test. For now we disable this plugin entirely.
See https://github.com/pytest-dev/pytest/issues/2430.

CI: Disable Pytest warnings plugin

---

joblib/_memory_helpers.py
joblib/func_inspect.py
joblib/test/test_format_stack.py
joblib/test/test_func_inspect.py
joblib/test/test_testing.py

If python 3.6 is run with the -Wd flags, DeprecationWarnings are thrown whenever a backslash is not used in an escape sequence. I fixed all these warnings, using raw strings where possible and double backslashes otherwise.

[MRG]: `DeprecationWarning: invalid escape sequence` in Python 3.6

---

CHANGES.rst
joblib/backports.py
joblib/test/test_backports.py
joblib/test/test_numpy_pickle.py

This is a fix for #540.
I also improved the test to actually test a multi-process concurrent access to the same target file.

[MRG] handle permission error in concurrency_safe_rename

---

joblib/func_inspect.py

Reduce the latency of the method call, especially in a big loop.
Please refer to issue -> https://github.com/joblib/joblib/issues/546
Fix #546.

Define namedtuple outside the method.

---

doc/parallel.rst
joblib/parallel.py

I think I updated all mentions of the multiprocessing backend to point to the new default loky backend instead.

[MRG] DOC update doc to mention the new loky backend

---

joblib/parallel.py
joblib/test/test_parallel.py

Now that joblib uses cloudpickle by default, any common Python callable (including lambda expressions) should be picklable so there is no point in paying that extra overhead.

[MRG] deprecate check_pickle in delayed

---

joblib/numpy_pickle.py

The `dump` method was modified to accept file objects instead of just file names.
This change is reflected in the documentation, but not in the function docstring.

Update docstring of `dump` to include use of file object

---

joblib/numpy_pickle.py

Added the use of file_like object in the doctring for the `load` method.
Did not find any other instances in the `numpy_pickle.py` module that required updating.

DOC: Fix docstring for `numpy_pickle.load`

---

joblib/numpy_pickle.py

Per the Python docs, the pickle `protocol` can be a negative integer.
Additionally, it is always an optional parameter.
I thought about elaborating on the usage in the `dump` docsting, but I think leaving it as "see pickle.dump documentation for more details" is fine?

DOC: Clarify type of pickle `protocol` parameter

---

joblib/_parallel_backends.py
joblib/test/test_parallel.py

This PR is an attempt to fix #533
It implements the 'reset backend dict' suggestion and adds a non regression test. This test checks that the dict is correctly reset after a job and that the computation time is stable across several runs.

Reset parallel batch statistics at the end of a run

---

joblib/parallel.py

Fixes #536. `Parallel` docstring now reflects the fact that total number of tasks is not printed in progress output until the iterator is consumed.

DOC Update Parallel docstring for progress output

---

.travis.yml
appveyor.yml

codecov 2.0.14 should have the fix from https://github.com/codecov/codecov-python/issues/135 so we don't need to do `codecov combine -a` before calling `codecov`.

[MRG] Test codecov fix and remove debugging code

---

doc/memory.rst
joblib/__init__.py

A side remark in the documentation of Memory, triggered by a mistake I've been doing repeatedly.

Note on persistent cache directory in doc

---

doc/memory.rst
joblib/__init__.py
joblib/_store_backends.py
joblib/disk.py
joblib/memory.py
joblib/test/test_disk.py
joblib/test/test_memory.py

~~This is a WIP PR just to check how this refactoring behaves on Windows~~. I'm also interested in API comments.
Normally tests should pass (at least on Linux/Python 3.5).
I tried to keep as much as possible the behavior of the test suite so normally it shouldn't introduce regression.
Here's a list of remaining things:

[MRG] Custom store backends API

---

doc/persistence.rst

This PR makes a small cleanup in the persistence documentation page:
* It fixes a typo in the first section title: s/Usecase/Use case/
* It rewords a few things, especially removing `we` from some directives. I prefer having something more neutral.

DOC: cleanup in persistence.rst

---

README.rst
doc/parallel_numpy.rst

This PR fixes small things in the parallel numpy documentation:
* fixes a typo and missing words
* avoid the use of `we` in some directives

DOC: reword a few things in parallel numpy documentation

---

doc/why.rst

Another documentation cleanup/rewording PR:
* replace other occurences of `we` by more neutral expressions
* remove extra title underline characters (=, -, .)

reword/cleanup a bit the "why" documentation page

---

joblib/_store_backends.py
joblib/memory.py
joblib/test/test_memory.py

This PR rename to `store_options` named parameter to `backend_options`, which is more in sync with the `backend` parameter.
This PR also improves the Memory documentation.

[MRG+1] memory: make API more consistent and improve documentation

---

doc/memory.rst

This PR tries to reword and cleanup a bit the memory documentation:
* avoid use of we/you
* fix a typo: usecase => use case
* cachedir => location parameter when instanciating a Memory
* removes extra underline characters

DOC: various enhancements in memory.rst documentation

---

Makefile
README.rst
continuous_integration/circle/build_doc.sh
doc/conf.py
setup.cfg
setup.py

As discussed earlier, this PR is an attempt to fix #622 
It removes the use of `python setup.py build_sphinx` to build the doc and adds 2 new targets in the project Makefile:
* doc-html: call sphinx-build directly in the `doc` directory to generate the documentation, with warning as errors
* doc-clean: clean documentation files and examples generated by the previous target
It also changes the examples thumbnail path: it should now work with readthedocs. Finally, I added a .PHONY statement in the Makefile (small cleanup, see [here](https://stackoverflow.com/a/2145605) for some details).

MAINT: build/clean sphinx documentation using Makefile targets

---

examples/nested_parallel_memory.py

I found these typos while reading the nested parallel memory example.

DOC: fix typos in nested parallel memory example

---

CHANGES.rst
joblib/_memmapping_reducer.py
joblib/test/test_memmapping.py

This is an alternative fix to #565 based on weakref callbacks. It completely removes the need to hash the arrays which should significantly reduce the dispatching overhead.
TODO

[MRG] Do not use expensive hash of arrays in auto-mmap

---

CHANGES.rst
doc/parallel.rst
doc/parallel_numpy.rst
joblib/_parallel_backends.py
joblib/parallel.py
joblib/test/test_parallel.py

Sorry, I deleted my remote branch by accident and it closed #595. Here is the same PR again.
This is an alternative implementation of #537. I reimplemented it from scratch because joblib had diverged a bit and I did not agree with the semantics of constraints violations in #537.
TODO:

[MRG+1] Backend hints and shared memory constraints

---

joblib/externals/loky/backend/popen_loky_posix.py
joblib/externals/loky/backend/queues.py
joblib/externals/loky/backend/semaphore_tracker.py
joblib/externals/loky/backend/spawn.py
joblib/externals/loky/backend/synchronize.py
joblib/externals/loky/process_executor.py

This fixes bugs in semaphore tracking and handling of the full queue exception when shutting down the executor.

loky 1.2.2

---

circle.yml
continuous_integration/circle/build_doc.sh

This PR is an attempt to move the circleci configuration file to v2.
I received a mail from them recently:
`You’ll need to update all of your config files to the CircleCI 2.0 syntax in order to migrate your projects to CircleCI 2.0 over the next 6 months.`

MAINT: move to circleci v2

---

CHANGES.rst

I realized that the new API and internal changes of Memory were not added to the changes.rst file.
This PR provides the update.

DOC: add notes about the recently merged store backend feature

---

joblib/memory.py
joblib/test/test_memory.py

Follow-up of #639 as suggested by this [comment](https://github.com/joblib/joblib/pull/639#issuecomment-372964288).

[MRG+1] FIX: fix misleading 'cachedir' deprecation warnings

---

doc/_static/custom.css

Fixes vertical space in sidebar for nested list (happens in pages deep in the docs, but not in the main docs).
Ping @aabadie

CSS: fix verticle space on RTD

---

Makefile
conftest.py
continuous_integration/travis/test_script.sh
doc/memory.rst
doc/parallel_numpy.rst
doc/persistence.rst

Until now we were not testing the doc rst files.
doctests from rst files in the `doc` folder are only run when numpy is installed and numpy >= 1.14.
Some doctests have been skipped in doc/memory.rst. It looks like this needs investigation because the behaviour has changed compared when it was written (joblib 0.8 allegedly). I'll create an issue about that.

[MRG+1] Fix rst doctests numpy 1.14

---

joblib/memory.py
joblib/test/test_memory.py

rather than a warning. There is no use case where allowing the user to set both cachedir and location is useful.

[MRG+1] Passing both location and cachedir to Memory should raise an error

---

CHANGES.rst
joblib/parallel.py
joblib/test/test_parallel.py

Fixes #652 
Currently when users want to use a separate backend (like dask) they wrap their code in a context manager
```python
with parallel_backend('dask'):
```
This is probably ideal for cleanliness, but can be somewhat awkward in interactive sessions.  It might be convenient to optionally allow users to set the parallel backend globally:
```python
parallel_backend('dask')
```
This PR implements this logic by converting the existing parallel_backend context manager into a proper context manager class, implementing `__enter__` and `__exit__`.  It now does the backend wiring on instantiation, rather than in `__enter__`.

Support using parallel_backend globally

---

doc/parallel.rst
joblib/memory.py
joblib/numpy_pickle.py
joblib/parallel.py

This PR should fix #663
- Link to Memory page is fixed
- a link to the Parallel page from the Parallel docstring is added
- links to the Persistence page from the load/dump function are added
- fixed automatic linking of the Parallel class in the Parallel rst page

DOC: improve cross-links in documentation

---

doc/memory.rst
examples/memory_basic_usage.py
examples/nested_parallel_memory.py
joblib/__init__.py

I feel this is better to make the doc compatible across different joblib versions. This is about the `cachedir/location` name change introduced by the store backends by @aabadie.
At the moment some of the doc on http://joblib.readthedocs.io/en/latest/ only works on master, which is fine but
1. you can still find it on google and be confused because the example does not work with the latest released joblib
2. even when we release joblib, the released scikit-learn will have an old joblib for a while so some examples will not work with `from sklearn.externals.joblib import ...`.
For completeness, the context I bumped into it was that I wanted to point some people to the nice examples on readthedocs except that they can not use it with the latest released joblib.

[MRG] DOC: remove Memory explicit cachedir and location named arg

---

joblib/memory.py
joblib/test/test_memory.py

Trivial PR to fix a harmless typo in a name.
It's a change of a private API. This could break people's code that use private API, hence the question is open of whether or not we should merge this.

MISC: fix typo in private function name

---

joblib/memory.py

The goal is to be consistent with the Parallel class documentation.
The docstring could also be extended with simple usage examples.

DOC: move memory doctring from __init__ to class level

---

CHANGES.rst
doc/parallel.rst
examples/parallel/distributed_backend_simple.py
joblib/parallel.py
joblib/test/test_parallel.py

Fixes https://github.com/joblib/joblib/issues/653
Currently when using external backends with joblib you need to know to
`import distributed.joblib`, which is not particularly intuitive.
```python
from joblib import parallel_backend
with parallel_backend("dask"):
pass
KeyError: 'dask'
```
Now implementers of downstream parallel backends can register small
functions within the Joblib codebase that register their backends
appropriately when triggered by users.
FWIW I suspect that not everyone will agree with this change.  I will not be surprised if it does not get merged.  It was simple enough to implement though that I thought I'd throw it up here just to make conversation about it easier.

Support registration of external backends

---

CHANGES.rst
joblib/_parallel_backends.py
joblib/format_stack.py
joblib/my_exceptions.py
joblib/parallel.py
joblib/test/test_my_exceptions.py
joblib/test/test_parallel.py

When doing nested parallel calls, all exception would be mapped to the generic `JoblibException` therefore losing the original exception type information (e.g. `ValueError`).
Furthermore, Python 3 already has a builtin `__cause__` exception nesting system that is used by default to trace exception that occurred on a remote worker process. The combination of the Python 3 `__cause__` nesting and the Joblib system yields overwhelmingly verbose and redundant exception reports.
To fix those two problems, we:
- disable useless exception wrapping under Python 3 to only rely on the built-in exception nesting mechanism;
- fix nested exception wrapping under Python 2 to preserve type information.

[MRG] Fix exception handling in nested parallel calls

---

joblib/_parallel_backends.py
joblib/executor.py

And change the default value to 5min.
I have noticed that initializing 88 Python workers on a machine with 88 logical CPUs and an NFS filesystem can take 20 to 30s. Therefore I think using 10s as default worker timeout is too low to be useful on large computing servers. I think 5 min is a more useful default value.
I think 5 min should also be the default value for loky itself.

[MRG] Make it possible to configure the reusable executor workers timeout

---

joblib/_parallel_backends.py
joblib/test/test_parallel.py

This does not protect against over-subscription but at least it protects against recursive thread bombs as reported initially in the tests of #690.

[MRG] Nested parallel call thread bomb mitigation

---

joblib/test/test_func_inspect.py
joblib/test/test_memory.py

Fixes #711  Declare as global these two functions which are not created in the normal way.  This PR helps both humans and linters to understand this unusual situation.

[MRG+1] global func_with_kwonly_args, func_with_signature

---

joblib/func_inspect.py
joblib/test/test_func_inspect.py

Fix for key error which were thrown from filter_args when default values were not specified for kw only arguments.
For example, in the following case arg_spec.kwonlydefaults is None:
```
def foo(x, *, y):
pass
filter_args(foo, [], [1], dict(y=2))
.../env/lib/python3.5/site-packages/sklearn/externals/joblib/func_inspect.py in <genexpr>(.0)
242     arg_defaults = arg_spec.defaults or ()
243     arg_defaults = arg_defaults + tuple(arg_spec.kwonlydefaults[k]
--> 244                                         for k in arg_spec.kwonlyargs)
245     arg_varargs = arg_spec.varargs
246     arg_varkw = arg_spec.varkw
TypeError: 'NoneType' object is not subscriptable
```
In another example, arg_spec.kwonlydefaults is not None, but it does not contain 'y':
```
def foo(x, *, y, z=3):
pass
filter_args(foo, …
```

fix kwonlydefaults key error in filter_args

---

joblib/memory.py

The warning currently says (from sklearn tests on travis):
```
E           DeprecationWarning: The 'cachedir' parameter has been deprecated in version 0.12 and will be removed in version 0.14.
E           You provided "cachedir='/tmp/tmpwewp89mm'", use "location=None" instead.
```
So it gives an incorrect alternative of `location=None` I think, while I assume it needs to be the same value as passed to cachedir? (which I did in this PR)

Fix cachedir deprecation message

---

doc/memory.rst
joblib/memory.py
joblib/test/test_memory.py

This PR is an attempt to fix #714:
- it reestablish the `argument_hash` attribute for backward compatibility, since it appears that some people were using it
- the argument_hash is now marked deprecated
- the string representation of MemorizedResult don't use `argument_hash` anymore but `args_id` instead.

FIX: re-establish argument_hash attribute for backward compat

---

.travis.yml
conftest.py
continuous_integration/appveyor/requirements.txt
continuous_integration/travis/install.sh
joblib/_dask.py
joblib/parallel.py
joblib/test/test_dask.py
joblib/test/test_parallel.py
setup.cfg

The manual and auto-scattering of numpy arrays disabled nested parallelism. To fix it's much easier to include the code of the backend as part of joblib itself.

[WIP] investigating with nested parallelism and dask

---

examples/compressors_comparison.py

The builds on read the docs are failing because of too high memory consumption. I suspect that it is due to the example comparing compressors, and I am trying to reduce the size of the data.
This should partially fix #724

DOC: attempt to fix the build on RTD

---

examples/compressors_comparison.py

This PR is an attempt to fix #724.
The idea is just to use less rows in the input dataset. Other changes are related to data displays.
This fixes the documentation build on ReadTheDocs, see [the generated documentation here](https://joblib.readthedocs.io/en/rtd_fix/auto_examples/compressors_comparison.html).
Some problems: the size of the dataset is now very small, so there's a lot of noise in the measured durations. This induces a lot of variations in the measures and sometimes LZ4 compression/decompression is slightly slower than raw (which is contradicting the example comments).

FIX: reduce dataset size in compressor example

---

README.rst
joblib/__init__.py
setup.py

fixes #737 
This PR replaces all occurrences of pythonhosted URL with the one on readthedocs.

MAINT: update documentation URL

---

CHANGES.rst
joblib/memory.py
joblib/test/test_memory.py

Fix #747
Just restoring how the `func` attribute of `MemorizedResult` is set. The `MemorizedResult` representation is the same between 0.11 and this PR.

FIX: MemorizedResult not picklable

---

examples/compressors_comparison.py

This PR increase significantly the dataset size used in the compressor comparison example. Now durations measured are more realistic and are more inline with the example conclusions.
This PR follows the conclusions provided in [this comment](https://github.com/joblib/joblib/pull/735#issuecomment-415016321).

DOC: fine tune compressor example dataset size for ReadTheDocs

---

joblib/test/test_parallel.py

This test should pass well, but appveyor is going to timeout because some semaphore trackers will not close properly.

Test that show failure to close semaphore trackers

---

CHANGES.rst
joblib/memory.py
joblib/test/test_memory.py

Fix #741. Close #743.
A few things:
* this does not address the `Memory` pickle being broken between joblib 0.11 and 0.12 mentioned in https://github.com/joblib/joblib/pull/743#discussion_r209727077. This potentially affects also scikit-learn 0.19 to 0.20 if you pickled estimators that use Memory (e.g. Pipeline, AgglomerativeClustering). This could be argued that we don't guarantee pickles compatibility between scikit-learn versions anyway. The error is quite misleading but at least this is an error and not a silent change ...
* it feels like there is some tension between hashing and cloning in the implementation of `__reduce__`. This PR is leaning towards cloning quite heavily but maybe a bit too much ...

FIX pickle roundtrip for Memory and related classes.

---

CHANGES.rst
joblib/memory.py

Here is a pull request that improves the performance of MemorizedFunc.call_and_shelve when a result has already been cached.
Basically, before the code request, joblib loads the entire cached file into memory, returns a reference to the file and forgets about what is in memory.
With this pull request, joblib creates the reference without loading the file into memory.
This PR  passed the Travis tests on my fork.
```python
import joblib
import numpy as np
memory = joblib.Memory("C:/TEMP/features/memory/")
@memory.cache
def large_array():
return np.random.normal(size=(100000,10000))
```
It takes 1m34s to create and return the cached array.
```python
%%time
a = large_array.call_and_shelve()
```
________________________________________________________________________________
[Memory] Calling …

Improved performance of call_and_shelve

---

joblib/_store_backends.py
joblib/memory.py
joblib/test/test_memory.py

Fix #764
A non regression test is also provided.
With this PR, the snippets provided in #764 not returns the following:
```python
In [1]: from joblib import Memory
In [2]: mem = Memory('/tmp/test')
In [3]: mem.store_backend
Out[1]: FileSystemStoreBackend(location="/tmp/test/joblib")
```
```python
In [2]: from joblib._store_backends import FileSystemStoreBackend
...: backend = FileSystemStoreBackend()
...: backend
...: 
Out[2]: FileSystemStoreBackend(location="None")
```

FIX: FileSystemStoreBackend string representation only returning location (path)

---

CHANGES.rst
joblib/memory.py
joblib/test/test_memory.py

While reading memory.py, it seemed to me that it should be possible to use the mmap mode when loading the cache fails.
This PR adds the test and fixes it. I refactored the function call in `_cached_call`, since it is used twice, and I think there is no difference between the two.
There is a small change in the behavior, that I thought was OK (do you agree ?) : 
There was this line: `args_id = None` which I think was not usefull. Removing it does not break any test and it does not match the docstring. 
https://travis-ci.org/MaximeWeyl/joblib/builds/421280052
https://github.com/MaximeWeyl/joblib/commit/c7bbaca03f821b9607449ce727d9a40421537280
So in this PR, I assumed I could forget about this line. Or maybe I should put it back.

Fixed bug : loading with corrupted cache with mmap mode

---

doc/_static/joblib_logo.svg

Fix #770 
This PR updates the joblib SVG logo:
- it embeds on the fly the Ubuntu Mono. This fix needs to be checked on a Windows or Mac machine first but it seems to work.
- it resizes slightly the logo width, I notived that the `b` of `lib` is scropped on the right. Moving the text to the right fixes this.

DOC: fix joblib logo rendering

---

doc/_static/joblib_logo.svg

Second attempt to fix #770.
This time the text elements are converted to path vectors. If this is merged, the text will not be editable directly via Inkscape but I think this is not important.

FIX: convert text element to vector path in svg logo

---

CHANGES.rst
joblib/_parallel_backends.py
joblib/test/test_parallel.py

The nested backend in `SequentialBackend` should not be changed as we do not got deeper in the nesting. This causes issue for libraries that relies on `Parallel` even when `n_jobs=1`, with subsequent nested calls (see _eg_ scikit-learn/scikit-learn#12389  ).
This PR should fix this and test the behavior.

FIX nested backend not changed by SequentialBackend

---

joblib/test/test_memory.py

This test verifies that the `call_and_shelve` function doesn't perform a load of cached data every time it is used.
The idea is to verify that the access time of the file containing the cached file. It should remain untouched after each calls. And getting result using `MemorizedResult.get` will change the access time since the data must be read.
See #757

memory: add test for call_and_shelve performance

---

doc/conf.py
examples/parallel_random_state.py
examples/utils.py
joblib/__init__.py
joblib/externals/loky/__init__.py
joblib/externals/loky/backend/__init__.py
joblib/externals/loky/backend/compat.py
joblib/externals/loky/backend/queues.py
joblib/externals/loky/backend/reduction.py
joblib/externals/loky/backend/utils.py
joblib/externals/loky/cloudpickle_wrapper.py
joblib/externals/loky/process_executor.py
joblib/externals/vendor_loky.sh
joblib/parallel.py
joblib/test/test_parallel.py

Bump the version of `loky` to 2.4.0.
This update changes the default behavior of `joblib`: `cloudpickle` is used by default to serialize the tasks. Note that this might cause some performance drop in particular for large python objects.

ENH update loky 2.4.0

---

CHANGES.rst
joblib/memory.py
joblib/test/test_memory.py

Closes #816 
Also raise a warning if location not None, but returned backend is None.

ENH Accept pathlib path for  store backend factory

---

CHANGES.rst
joblib/_dask.py
joblib/parallel.py
joblib/test/test_dask.py
joblib/test/test_parallel.py

This is a fix for #828.
<del>I still need to change the dask backend to add an option to wait for workers coming up (with a timeout) in the dask backend itself.</del>
It consists in two parts:
- first joblib will now throw a RuntimeError for any backend that return n_jobs=0 in its configuration step;
- second, the `DaskDistributedBackend` will now wait a configurable amount of time for workers to come up by scheduling a small probe task if the client sees 0 workers at configuration time.

FIX explicit error when effective_n_jobs is 0

---

CHANGES.rst
joblib/__init__.py
joblib/externals/cloudpickle/__init__.py
joblib/externals/cloudpickle/cloudpickle.py
joblib/test/test_parallel.py

This PR upgrades the vendored cloudpickle to version 0.8.0.
Consequenlty, it solves the issues  #833  and #836, reporting that changes of global variables in the environment of a `joblib.Parallel` process would not be propagated in the workers.
A non-regression test is also added to make sure this bug is solved.

Upgrade to cloudpickle 0.8.0

---

conftest.py
joblib/test/test_dask.py

This allows to clean up a few (slightly confusing IMO) flake8 noqa markers. Also it feels more consistent with pytest philosophy that fixtures are defined in conftest.py and "magically" (i.e. without explicit import) available in test files.

[MRG] Import loop fixture in conftest.py

---

joblib/_memmapping_reducer.py
joblib/test/test_memmapping.py

Fix #839: when a Numpy array is created directly with Python's mmap, joblib was crashing because it assumes that all mmap arrays use np.memmap. The latter has more attributes (offset, filename) that are used by joblib to recreate the memmap array instead of pickling the data, which is a nice feature, but it cannot be done with pure mmap arrays.

Fix use of mmap arrays (when not using np.memmap)

---

continuous_integration/travis/install.sh
continuous_integration/travis/test_script.sh

Now that joblib is no longer vendored in scikit-learn, there is no longer any need to vendor

MAINT test against the latest stable scikit-learn version

---

joblib/_store_backends.py

This addresses issue #672 by improving the robustness of Memory.reduce_size to race conditions that arise when multiple processes are trying to delete the same directory simultaneously. Python 3 raises a OSError in this context, whereas Python 2 raises an IOError. This update catches and ignores both types of errors.
Fix #672.

Stale file handle IOError in Memory.reduce_size on Python 2

---

CHANGES.rst
doc/persistence.rst
joblib/numpy_pickle.py
joblib/numpy_pickle_compat.py

Update the documentation to make it explicit that joblib.load should never be used to load files from an untrusted source.
Also add compat for numpy 1.16.3 and later.

DOC emphasize security sensitivity of joblib.load

---

joblib/_compat.py
joblib/_multiprocessing_helpers.py
joblib/test/test_module.py

Change the way we check for semaphore availability to avoid spawning resource trackers on `joblib` import.
I rely directly on `SemLock` for unix and did not change the bahavior on windows as there is no semaphore tracker in this case.
closes #841

FIX avoid spawning resource trackers on import

---

setup.py

Hello,
As far as I can see on CI, Python 3.7 is already supported, but it's not declared in the `classifiers` list at `setup.py`.
Best regards!

Add a missing classifier for Python 3.7

---

.travis.yml
continuous_integration/circle/build_doc.sh
continuous_integration/travis/install.sh
continuous_integration/travis/test_script.sh
joblib/test/test_dask.py

Fix miscellaneous CI failures.

update joblib CI scripts

---

CHANGES.rst
joblib/hashing.py
joblib/test/test_module.py

Fixes #927 to support Python 3.8.

Support Python 3.8

---

CHANGES.rst
joblib/_parallel_backends.py
joblib/parallel.py
joblib/test/test_parallel.py

Another solution to fix #865 without explicitly asking for it.
Here, the protection against nested call is implemented to only be used in nested Parallel calls.

ENH only protect against nested call in Parallel

---

CHANGES.rst
joblib/_dask.py
joblib/test/test_dask.py

Builds on top of #910 
Fixes #852 
(I'm still not 100% sure of whats going on here). This PR ensures the synchronous execution of distributed `scatter` operations by not running joblib's callbacks directly into `distributed` client event loop. In this situation, the operations can safely be made blocking.
I tried running the sklearn example in #852 and it runs fine. Hopefully the results are correct also.
@ogrisel

Fix dask scatter deadlock

---

CHANGES.rst
joblib/_parallel_backends.py
joblib/parallel.py

This PR tries to improve load-balancing between workers in joblib, mostly in two ways, creating balanced batches both in terms of number of tasks, and in terms of total batch running time.
Previously, the tasks iterator consumed by joblib was sliced `batch_size` tasks at a time. This can lead to unbalanced batches when we reach the end of the iterator.
I propose to slice the tasks iterator `batch_size * n_jobs` tasks at a time instead. The resulting `n_jobs` batches are not dispatched immediately, but stored in a local queue that the further callback-triggered `dispatch_one_batch` calls will try to access before re-slicing the iterator. If the queue is empty, then the batch-size is re-computed, the iterator is re-sliced, and the queue is re-populated.
The higher the running-time variance …

ENH Improve load-balancing between workers for large batch sizes.

---

CHANGES.rst
continuous_integration/appveyor/requirements.txt
continuous_integration/travis/install.sh
doc/parallel.rst
joblib/__init__.py
joblib/_parallel_backends.py
joblib/executor.py
joblib/externals/loky/__init__.py
joblib/externals/loky/backend/fork_exec.py
joblib/externals/loky/backend/popen_loky_posix.py
joblib/externals/loky/backend/popen_loky_win32.py
joblib/externals/loky/backend/process.py
joblib/externals/loky/backend/spawn.py
joblib/externals/loky/process_executor.py
joblib/externals/loky/reusable_executor.py
joblib/parallel.py
joblib/test/test_parallel.py
setup.cfg

Vendor the version 2.6 of `loky` in joblib. This version introduce a way to set the environment variables in the child process before loading any module. This PR intend to use it to specify the maximal number of inner threads `max_inner_num_threads` in the child processes. This would fix #880 and #913 .

ENH over-subscription mitigation + MTN vendor loky 2.6

---

joblib/parallel.py

I was surprised that `Parallel(backend='loky', prefer='threads')` doesn't error

DOC minor update about prefer parameter

---

doc/parallel.rst

This fixes a few misspellings and updates a few sentences to use more idiomatic English.

Fix a few typos in the docs (parallel.rst)

---

.travis.yml
appveyor.yml
conftest.py
continuous_integration/travis/test_script.sh
joblib/test/test_hashing.py
setup.cfg

This is a test PR to check if we can reproducing some of the spurious CI failures found in #968.
In particular the `test_hashes_stay_the_same` failure of:
https://ci.appveyor.com/project/joblib-ci/joblib/builds/29384100

CI failing fixes (sklearn doctests and joblib.hash on windows)

---

CHANGES.rst
joblib/executor.py
joblib/test/test_parallel.py

Closes #967 
Correctly assess if a new executor needs to be spawned of the previous one can be reuse and add a non-regression test.

FIX loky workers not reused for multiple Parallel calls

---

doc/parallel.rst

Update joblib page to list Spark as one of the backends

[ML-9113]  Update joblib page to list Spark as one of the backends

---

conftest.py

This should help tracking the cause of the problem reported in #974.

Setup faulthandler.dump_traceback_later after pytest

---

CHANGES.rst
continuous_integration/travis/install.sh
joblib/parallel.py
joblib/test/test_parallel.py

closes #984 
When `n_jobs=None` is passed to `effective_n_jobs`, the number of reported jobs should be equal to either 1 or the default in the current backend.

BUG fix reported number of jobs in effective_n_jobs

---

joblib/test/test_module.py

Janek beat me to fix the typo in docs in 427e7c6a8937acdd24d07e04910c794e767cff59, but I found it manifested in the test name! ;)

Fix a minor typo in a test name

---

.travis.yml
joblib/_dask.py

`distributed` 2.10 throws a new type of `TimeoutError`, so the dask backend of `joblib` needs to be updated to except new such exceptions.

catch new TimeoutError thrown by distributed

---

continuous_integration/appveyor/requirements.txt
continuous_integration/travis/test_script.sh

Fixes #1014 
Now that the scikit-learn/scikit-learn#5846 is present in `scikit-learn` latest release, we can remove the related workarounds that were introduced in joblib before this fix.

Fix sklearn's CI entry

---

doc/memory.rst
doc/parallel_numpy.rst

This patch fixes a few typos that I found in the documents.

DOC fix a few typos

---

azure-pipelines.yml

macos-10.13 is being removed:
https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/

MAINT use macos-10.14 on Azure

---

joblib/_parallel_backends.py

Here is a more subtle `Python 2` leftover:
Now that `joblib` is `Python 3` only, it can directly rely on `concurrent.futures._base.TimeoutError`
instead of `loky._base.TimeoutError`, which are the same objects in `Python 3.3+`
This need to be merged to make `joblib` compatible with the `Python 3`-only `loky` in joblib/loky#227.

CLN directly use concurrent.futures TimeoutError

---

joblib/_memmapping_reducer.py
joblib/test/test_memmapping.py

In response to https://github.com/joblib/joblib/pull/966#issuecomment-619035841

Add a retry mechanism to the resource_tracker when unlinking memmaps

---

joblib/_dask.py
joblib/test/test_dask.py

Previously we would wait until joblib called lazy_result.get() before
collecting results.  This would trigger a transfer in the main thread,
which would block things a bit.
Now we collect results as soon as they are available using
dask.distributed.as_completed.  This helps to reduce overhead in joblib
a bit and improve overall bandwidth.
Somewhat related to (but doesn't entirely fix) https://github.com/joblib/joblib/issues/1020 and https://github.com/dask/dask/issues/5993
There are still performance issues.  We have a lot of downtime in this process, but it's not happening in Dask (all of our profilers show that we're not spending a ton of time in Dask code).  I suspect that something on the joblib end is blocking things, but profiling so far hasn't shown anything.

Collect Dask results as they complete

---

joblib/numpy_pickle.py
joblib/numpy_pickle_compat.py
joblib/test/data/create_numpy_pickle.py
joblib/test/test_numpy_pickle.py

`tostring` is [deprecated](https://numpy.org/devdocs/reference/generated/numpy.ndarray.tostring.html#numpy.ndarray.tostring). This PR replaces `tostring` with `tobytes`.

MNT Replaces tostring with tobytes

---

CHANGES.rst
joblib/_dask.py
joblib/_parallel_backends.py
joblib/test/test_dask.py

Until now, the `DaskDistributedBackend` would use `ParallelBackendBase`'s `compute_batch_size` method instead of `AutoBatchingMixin`'s `compute_batch_size`. The first one is actually a smoke method always returning 1, so the `dask` backend would always use a  batch size of 1 when submitting tasks.
This PR fixes this.
This also needs a quick test.

Fix a bug preventing the dask backend to use auto-batching.

---

joblib/parallel.py

I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …

Fix exception causes in parallel.py

---

CHANGES.rst
azure-pipelines.yml
joblib/_dask.py
joblib/parallel.py
joblib/test/test_dask.py
joblib/test/test_parallel.py

`joblib.Parallel` objects submit stateful callables to `dask`'s scheduler, which seems goes against `dask`'s assumption, which is that one should submit [pure functions](https://en.wikipedia.org/wiki/Pure_function).
Because of this assumption, `dask` sets up a pickle cache in the workers when deserializing submitted functions. This does not cause any harm in the pure function setting, but it does when one submits two *different* (e.g different id in the original interpreter), **stateful** callables with the same pickle bytes representation. In this situation, when deserializing the second callable, the pickle cache is hit, and the deserialized objects points to the first callable. This results in the first callable's state being mutated concurrently, and yields cryptic errors, especially …

Fix a bad interation with dask.distributed pickle cache

---

CHANGES.rst
joblib/_dask.py
joblib/test/test_dask.py

Workaround for dask/distributed#3703, which affects the `joblib-dask` integration.
When scattering data inside `dask` worker, task using this data can often end up being cancelled, see the referenced issue for more information.
This situation typically happens inside `joblib` during nested `Parallel` calls (whenn the inner parallel call scatters some data).
As suggested by @mrocklin, another workaround is to use `hash=False` inside `client.scatter` calls -- I'd like to compare the two solutions via a few benchmarks before merging this PR.
Related, but does not fix entirely #959 
This also needs tests.

[MRG] Don't scatter data inside dask workers

---

.codecov.yml
CHANGES.rst
joblib/_dask.py
joblib/parallel.py

@ogrisel this PR should fix https://github.com/joblib/joblib/issues/959#issuecomment-652329167. Feel free to checkout this PR and try it out on your machine using #959's repro.
```
task: <Task pending name='Task-6045' coro=<DaskDistributedBackend._collect() running at /home/ogrisel/code/joblib/joblib/_dask.py:197> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fae2aaf0b50>()]> cb=[IOLoop.add_future.<locals>.<lambda>() at /home/ogrisel/miniconda3/envs/pylatest/lib/python3.8/site-packages/tornado/ioloop.py:690]>
```
This PR only highlights the problem (`terminate` will destroy `_collect` while `_collect` has not had the time to exit yet.
I'm not against using a strong synchronization primitive, but we would need to be careful about it.

[MRG] Fix a race condition during joblib's dask backend termination

---

joblib/func_inspect.py
joblib/memory.py
joblib/test/test_memory.py

Fixes #1035
cc @ogrisel - I need to test a few more cases, but it should be reviewable.

Prevent spurious cache clearing when calling a cached func inside a Parallel call

---

joblib/func_inspect.py
joblib/test/test_memory.py

Fixes #1096
This PR changes the cache directory from
`[...]/joblib-__ipython-input__/<TheFunctionName>/`
to
`[...]/joblib-<ipython-input-XYZ>/<TheFunctionName>/,`
where `XYZ` comes from `co_filename` and is a hash of the function.
Ideally this should probably use the `.ipynb` filename  but I don't think we can retrieve it easily, and it wouldn't work for pure IPython sessions.
I'm not sure how to test this?

Avoid Memory collision between notebooks with same function name

---

CHANGES.rst
joblib/parallel.py
joblib/test/test_parallel.py

**Context**: `check_pickle` should have been removed in 0.13.0 as indicated in the `DeprecationWarning`.
**Changes**: This PR removes this argument, behavior, and the associated test.
**Associated Issue:**  #900

Remove `check_pickle` argument in `delayed`.

---

conftest.py
joblib/test/test_dask.py

https://github.com/dask/distributed/tree/b2f594e69751e0733ac595026e04181c55119ae9 changed the `IOLoop` closing logic of  `distributed`, and some test of ours need to be ajusted. It may be a good time to bump the `distributed` version, or test this version of distributed in another existing CI entry. Otherwise someone can just test this PR locally too.
cc @ogrisel @tomMoral

Update some joblib-dask integration tests

---

examples/parallel_random_state.py

On windows, the default start_method is "spawn" which causes a freeze or a crash when running `examples/parallel_random_state.py `.

MAINT make it possible to build the doc without fork start_method

---

joblib/memory.py

There is a small typo in joblib/memory.py.
Should read `utilities` rather than `utilitiees`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, utilitiees -> utilities

---

joblib/memory.py

Fix #574.
The link does not seem to be created in the locally generated HTML for some reason, but good enough for now.

DOC: improve Memory bytes_limit documentation.

---

CHANGES.rst
joblib/func_inspect.py
joblib/test/test_memory.py

Use inspect.signature() instead of inspect.getfullargspec()

---

joblib/memory.py

Improve docstring for `byte_limit` to explain how the deleted items are selected.
Closes #1170

DOC explain Memory byte_limit behavior

---

CHANGES.rst
doc/conf.py
examples/serialization_and_wrappers.py
joblib/_dask.py
joblib/externals/loky/backend/queues.py
joblib/externals/loky/backend/resource_tracker.py
joblib/externals/loky/backend/spawn.py
joblib/externals/loky/backend/utils.py
joblib/test/test_hashing.py
joblib/test/test_memory.py
joblib/test/test_parallel.py

Fixes some typos (assisted by https://github.com/bwignall/typochecker ).
I'll highlight upfront that `CHANGES.rst` has a few updates in this PR; please let me know if you would like the originals preserved.

DOC: fix typos

---

CHANGES.rst
joblib/numpy_pickle.py
joblib/numpy_pickle_compat.py
joblib/numpy_pickle_utils.py
joblib/test/test_numpy_pickle.py

- Addressing https://github.com/joblib/joblib/issues/1123

Fixing byte-order consistency/mismatch for cross-endian platform

---

setup.cfg

Fix the following setup.py warning:
/usr/lib/python3.10/site-packages/setuptools/dist.py:691: UserWarning: Usage of dash-separated 'doc-files' will not be supported in future versions. Please use the underscore name 'doc_files' instead

MAINT fix setup.py warning

---

joblib/parallel.py

Update to better describe mmap_mode parameter for Parallel class. Reword as needed...

Update of mmap_mode description

---

CHANGES.rst
joblib/func_inspect.py

As mentioned in #1210, this adds handling of a different cell code naming scheme in the newest Jupyter notebook / IPython version  (at least as packaged on Arch Linux).
Let me know if anything else can / needs to be done.
Cheers!

Handle new naming scheme in newer Jupyter notebook

---

.readthedocs-requirements.txt
joblib/_dask.py
joblib/_parallel_backends.py
joblib/test/test_dask.py

When trying to use joblib inside a Dask worker, the warning is not super helpful.
```
UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
```
Probably better to point to the fact that you can start Dask workers in non-daemonic mode.
A case where this setup makes sense is if you combine dask-jobqueue to launch multiple jobs on a HPC cluster and then use joblib to do some parallel computation within each job.
To be fair, I don't know whether there is any caveats in having non-daemonic Dask workers and I could not find anything in the Dask documentation.
The only thing I found was about why multiprocessins launch processes in daemonic mode:
https://mail.python.org/pipermail/python-list/2011-March/750543.html

Add more user-friendly warning about using joblib inside a Dask worker.

---

joblib/memory.py
joblib/test/test_hashing.py
joblib/test/test_memory.py

Hi there,
While cleaning up some deprecation warnings in Nilearn, I realized that a few of them were due to our use of `cachedir` instead of `location`, which has been deprecated since joblib `0.12` and was scheduled to be removed in `0.14` (see https://github.com/nilearn/nilearn/pull/3037).
I'm not sure whether keeping it despite the fact that the deprecation cycle has been finished for a while is intentional or not. If it isn't, this PR proposes to remove it and update the corresponding tests. Feel free to close it otherwise.

Remove deprecated `cachedir`

---

README.rst
azure-pipelines.yml
continuous_integration/install.sh
continuous_integration/run_tests.sh
joblib/test/test_deprecated_objects.py
joblib/test/test_memmapping.py
setup.py

Loky is about to do a big spring cleanup  to remove all hard to maintain backports for Python versions in the range [2.7-3.6].
Furthermore we have failing tests with joblib on Python 3.6. Let's not waste scarce maintainer's time on no longer supported Python versions.

Drop 3.6 support

---

joblib/numpy_pickle.py
joblib/test/test_numpy_pickle.py

We support python >= 3.6. pathlib has been added in 3.4: https://docs.python.org/3/library/pathlib.html?highlight=pathlib#module-pathlib.

Remove some compat code for old Python versions

---

azure-pipelines.yml
continuous_integration/run_tests.sh

This should fix the sklearn test setup by making pytest not try to collect tests on unrelated XML files with missing read permission in the `/tmp` folder.

MAINT fix sklearn test setup

---

continuous_integration/install.sh

similar to https://github.com/joblib/joblib/pull/1261 but for pypy
Also tweak the comments, I don't think this causes freezes but only test errors because there are additional PytestRemovedIn8Warning (but maybe I missed something ...)

MAINT: pin pytest<7 in pypy3 CI

---

CHANGES.rst
joblib/_memmapping_reducer.py
joblib/disk.py
joblib/test/test_memmapping.py

Blindly trying something on the CI.
I cannot reproduce the race condition on my laptop unfortunately.
Furthermore it seems that we also observe this test failing on one of the macos builds with the multiprocessing backend although I am not 100% sure why.

Fix remaining resource_tracker-related test warning failures

---

joblib/backports.py

Temporary mitigation for https://github.com/scikit-learn/scikit-learn/issues/22614 .
To be removed 6 months or so after the release of scikit-learn 1.1.

FIX keep on importing distutils for now

---

CHANGES.rst
joblib/externals/cloudpickle/__init__.py
joblib/externals/cloudpickle/cloudpickle_fast.py
joblib/externals/cloudpickle/compat.py

Towards a true fix for the https://github.com/scikit-learn/scikit-learn/pull/24376 workaround to add support for PyPy 3.8+.

cloudpickle 2.2.0

---

continuous_integration/run_tests.sh
joblib/test/test_parallel.py

Fixes #1307
Although this causes a deadlock in the `_python_exit` function of loky when loky is nested under loky.
We would need to craft a minimal reproducer for loky itself.

Fix test_nested_parallel_warnings with pytest 7+

---

CHANGES.rst
joblib/_utils.py
joblib/parallel.py
joblib/test/test_utils.py

I realized https://github.com/joblib/joblib/pull/1321 doesn't actually fix the issue, since `eval("exec('import os')", {}, {})` would still work.
This PR uses AST and limits the operations to the very basic ones.
This should be an actual fix for https://github.com/joblib/joblib/issues/1128
cc @ogrisel

FIX parse pre-dispatch with AST instead of calling eval

---

joblib/test/test_parallel.py
joblib/testing.py

`test_parallel_with_interactively_defined_functions_default_backend` happens to be killed from time to time on the slow macos CI host and the error message was not informative.
Using faulthandler in the subprocess script instead should help although I suspect that this wasn't really a deadlock but that the previous 5s timeout was too short for the slow CI host.
Let's see.

Make test  timeout more informatively on macos CI

---

continuous_integration/install.sh
joblib/test/test_memmapping.py

Trying to use the latest versions of pytest and coverage and attempting to avoid a random failure of `test_child_raises_parent_exits_cleanly` on macos CI.

[MAINT] various test updates

---

joblib/test/test_memmapping.py

This tests tends to fail randomly on the macos CI where `os.path.exists` seems to not be reliable even after 100 attempts spanning 10s.
As an alternative, try to write into the temp folder to check for its existence so as to force any FS-level cache invalidation.

Test child raises parent exits cleanly more reliable on macos

---

setup.cfg

It was removed in https://github.com/joblib/joblib/pull/525, not sure whether this is still needed. At least locally the test pass on my machine with the changes in my PR.
Context: I was trying to trigger warnings due to `pytest.warns(None)` and pytest 7 and could not see them. https://docs.pytest.org/en/7.0.x/deprecations.html#using-pytest-warns-none
Probably it would be good to get the `pytest.warns(None)` replacement from https://github.com/joblib/joblib/pull/1264

MAINT add back pytest warnings plugin

---

joblib/test/test_memmapping.py

Apparently this flaky test only fails for the non-default multiprocessing backend. While it would be nice to find a way to fix it, it seems particularly difficult to investigate.
Let's mark it as XFAIL for now while referencing the existing open issue #1086.

XFAIL test_child_raises_parent_exits_cleanly with multiprocessing

---

continuous_integration/install.sh
joblib/test/test_dask.py
joblib/test/test_numpy_pickle.py
joblib/test/test_parallel.py

try to see if we can use `pytest7` by removing `warns(None)`.

MAINT: remove pytest.warns(None) warnings in pytest 7

---

CHANGES.rst
azure-pipelines.yml
joblib/externals/loky/__init__.py
joblib/externals/loky/process_executor.py
joblib/test/test_memmapping.py

Let see if the fixed process management of loky make the joblib CI more stable.

CI test the future loky-3.3.0 branch

---

joblib/test/test_numpy_pickle.py

There still remain a few occurrences of `np.matrix` for the pickle compat tests. Cleaning those would require regenerating the stored pickled files with old Python & joblib versions.
We can do that in a later PR ;)

MAINT cleanup numpy warnings related to np.matrix in tests

---

doc/memory.rst

DOC: Document cache hit function

---

CHANGES.rst
joblib/numpy_pickle.py

This pull request ensures native byte order for numpy memmap ndarray, generalizing the fix for ndarray applied in #1181.
It is supposed to fix #1353.
Thanks for considering it.

Ensure native byte order for memmap.

---

CHANGES.rst
joblib/_memmapping_reducer.py
joblib/test/test_memmapping.py

Closes https://github.com/joblib/joblib/issues/902
In this case when 'os' has no attribute 'statvfs' we don't use `/dev/shm` even if it exists, as we are then not able to determine how much free space it has.
The other possible solution could be to ignore `SYSTEM_SHARED_MEM_FS_MIN_SIZE` and still write to `/dev/shm`.
The typical use case where this could happen is when running a Linux like system on Windows (which doesn't have statvfs apparently). I'm not sure what would be better.

Fix memmapping_reducer when 'os' has no attribute 'statvfs'

---

azure-pipelines.yml

MAINT pin flake8<6 on the CI

---

joblib/test/test_numpy_pickle.py

I have noticed `OSError: [Errno 98] Address already in use` with `nogil` when running multiple times the following command:
```
pytest joblib/test/test_numpy_pickle.py -k socket
```
```
================================================ test session starts ================================================
platform linux -- Python 3.9.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/lesteve/dev/joblib, configfile: setup.cfg
plugins: timeout-2.1.0, forked-1.4.0, flaky-3.7.0, xdist-3.1.0
collected 130 items / 129 deselected / 1 selected                                                                   
joblib/test/test_numpy_pickle.py F                                                                            [100%]
===================================================== FAILURES …
```

TST Close client in test_pickle_in_socket

---

CHANGES.rst
joblib/_store_backends.py
joblib/memory.py
joblib/test/test_store_backends.py

Currently, when caching fails because the function output can't be pickled, there is no warning, but the output will not be cached. This surprises users, who expect their output to be cached.
This is related to https://github.com/joblib/joblib/issues/952 and https://github.com/joblib/joblib/issues/896 . It does not solve the underlying race condition in https://github.com/joblib/joblib/issues/896, but it does implement the suggestion made by @tomMoral [in this comment](https://github.com/joblib/joblib/issues/952#issuecomment-546370327): it just raises an error when the caching fails due to pickling.

Do not swallow PicklingError

---

azure-pipelines.yml
pyproject.toml

Fixes #1388.
Python 3.11 is already supported but is not tested and documented as such.
This updates the CI and adds a classifier for Python 3.11 to update the metadata.

MAINT Explicit support for Python 3.11

---

benchmarks/bench_sequential_fast_tasks.py

Add a benchmark script to test the overhead of calling `joblib` with `n_jobs=1` vs calling a sequential loop for `numpy` matrix multiplications with various matrix sizes and for a very fast function (in red).
This gives
here, we can see that for small tasks, we have an overhead of roughly x10 per task for tasks that takes 1ms.
This state should be corrected by the changes pushed in #588.

BENCH add benchmark script for n_jobs=1

---

joblib/test/test_memmapping.py

Another test fix for Python nogil

TST Fix test_memmapping for Python nogil

---

continuous_integration/install.sh

The `codecov` package is deprecated and we actually don't need it so it should be safe to remove it.

FIX upload to codecov

---

joblib/externals/loky/__init__.py
joblib/externals/loky/_base.py
joblib/externals/loky/backend/__init__.py
joblib/externals/loky/backend/_posix_reduction.py
joblib/externals/loky/backend/_win_reduction.py
joblib/externals/loky/backend/context.py
joblib/externals/loky/backend/fork_exec.py
joblib/externals/loky/backend/popen_loky_posix.py
joblib/externals/loky/backend/popen_loky_win32.py
joblib/externals/loky/backend/process.py
joblib/externals/loky/backend/queues.py
joblib/externals/loky/backend/reduction.py
joblib/externals/loky/backend/resource_tracker.py
joblib/externals/loky/backend/spawn.py
joblib/externals/loky/backend/synchronize.py
joblib/externals/loky/backend/utils.py
joblib/externals/loky/cloudpickle_wrapper.py
joblib/externals/loky/initializers.py
joblib/externals/loky/process_executor.py
joblib/externals/loky/reusable_executor.py

The very big log is due to the blackification of `loky` :smiling_face_with_tear: 
This should hopefully help with the CI stability as we fixed some strange stuff...

MTN vendor loky 3.4.0

---

joblib/test/test_parallel.py

This test causes a deadlock reliably on pypy.
Skipping to make CI on `master` run again but this should be properly investigated in a dedicated PR.

MTN skip thread_bomb mitigation test on PyPy for now

---

joblib/logger.py
joblib/memory.py
joblib/test/test_logger.py
joblib/test/test_memory.py

I found this feature useful when inspecting the synchronisation of caches between a remote and local machine. In particular, it can happen that arguments are hashed differently depending on the platform. 
For example, this inspection revealed that 
1. class-valued arguments were stored at a different location in memory and therefore had different hashes, as their str representation is different, and 
2. some numerical arguments that did result from a numerical did not agree because of floating point inaccuracies in their value.
In logging the arguments and their hash, I was able to track down and resolve those differences so that syncing the caches does now work.

High verbosity mode that prints arguments, hash and store location.

---

continuous_integration/run_tests.sh
joblib/test/test_parallel.py

Investigation PR for #1150 
From the investigation, this bug seems to be related to a bad interaction between the test, Pypy and `coverage`.
I propose to disable the coverage on this test to stabilize the test suite.
I was able to reproduce the failure locally by running the test with `--cov=joblib` and by adding the following at the beginning of the test:
```python
def test_thread_bomb_mitigation(backend):
def recursive():
return recursive()
with raises(RecursionError):
recursive()
```
This could be investigated further if someone has the time to do so.

DBG try to debug the thread_bomb_mitigation test

---

.gitignore
benchmarks/bench_grid_search_scaling.py

Add a benchmark to compare `joblib` scaling for a `GridSearch` on synthetic data.
This benchmark allows to compare 2 versions of `joblib` by running it multiple times.

BENCH scaling of a GridSearch with n_jobs

---

.readthedocs.yaml
doc/Makefile
doc/_templates/class.rst
doc/index.rst
doc/memory.rst
doc/parallel.rst
examples/parallel_generator.py
examples/serialization_and_wrappers.py
joblib/_cloudpickle_wrapper.py
joblib/compressor.py
joblib/hashing.py
joblib/numpy_pickle.py
joblib/numpy_pickle_compat.py
joblib/parallel.py
joblib/test/test_cloudpickle_wrapper.py
readthedocs.yml

Closes #1436
1. `SPHINXOPTS` wasn't used in `doc/Makefile`, now it is so you can do stuff like `make clean && make html SPHINXOPTS="-nWT --keep-going -D sphinx_gallery_conf.filename_pattern=none"`
2. Modify `SPHINXOPTS` to use `-nWT --keep-geing` to be nitpicky
3. Fix a bunch of nitpicky problems
There are a few left I still need to sort out but this is at least close to working locally.

MAINT: Be nitpicky about docs

---

joblib/logger.py

Duplicate of #1033 that I closed by mistake.

CLN tidy logger

---

doc/index.rst
doc/parallel.rst

It seems that parallel_config was not very visible in the docs.
This is a quick fix to improve a bit the situation.
We should probably adapt more our docs, but I only have a little bit of time.

Document parallel_config

---

examples/compressors_comparison.py

Host the data directly on github for more stable download in the examples.

DOC example data DL from GH

---

CHANGES.rst
doc/parallel_numpy.rst
joblib/_memmapping_reducer.py
joblib/executor.py
joblib/externals/loky/reusable_executor.py
joblib/numpy_pickle.py
joblib/test/test_parallel.py

Hello there, `joblib` maintainers! 
thank you for your hard work. I came here because a useful warning had a typo in it, "..loaded from the file **redacted** is not not bytes aligned." and noticed that there was another instance of a `not not` typo elsewhere in the repository. Unsatisfied to fix just those two "not not" instances, I decided to regex for others, and here's the result.
For the record, the incantation I used was `git grep -E "\b(\w+)\s+\1\b"` and the few remaining results for this are legitimate ("Matrix Matrix multiplication", for example).
Happy hacking! :bowtie:

fix double repeated word typos

---

doc/conf.py
doc/parallel.rst
examples/parallel/distributed_backend_simple.py
examples/serialization_and_wrappers.py
joblib/_dask.py
joblib/_parallel_backends.py
joblib/parallel.py
joblib/test/test_config.py
joblib/test/test_dask.py
joblib/test/test_parallel.py

Follow up for #1451 to use `parallel_config` as much as possible in examples and in the tests.
In doing so, I realized that it actually has a different behavior than `parallel_backend`.
This PR does:
- make it possible to specify the `default_n_jobs` per backend (in particular to have default `n_jobs=-1` for dask).
- Fix the nested `parallel_config` usage. Calling the two following examples is equivalent while the first one would give `LokyBackend` with `2` jobs with the current version on `master`.
```python
with parallel_config(backend='threading'):
with parallel_config(n_jobs=2):
p = Parallel()
with parallel_config(backend='loky', n_jobs=2):
p = Parallel()
```

DOC reference parallel_config instead of parallel_backend

---

CHANGES.rst
joblib/parallel.py
joblib/test/test_config.py

Fixes #1473 
Even if the new default value of `n_jobs` is a sentinel object, I think that we should not interpret `n_jobs=None` as explicitely set because it used to mean 'unset'. Instead we should treat it identically as if it were left to its default value.

FIX treat n_jobs=None as if left to its default value

---

CHANGES.rst
benchmarks/bench_pickle.py
joblib/_memmapping_reducer.py

This PR addresses changes introduced in https://github.com/numpy/numpy/pull/24540 and https://github.com/numpy/numpy/pull/24376 relevant to NEP 52.

MAINT: Update byte_bounds import

---

joblib/numpy_pickle_utils.py

Hi!
This PR reflects changes introduced in https://github.com/numpy/numpy/pull/24682.

MAINT: Cleanup expired ndarray methods

---

README.rst

GitHub does, for good reasons, no longer support the `git://` protocol.
https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

Fix README cloning url

---

README.rst

1. https://github.com/joblib/joblib/archives/master now returns a 404 response
2. It would appear as if GitHub now only provide ZIP archives

Fix README archive download link

---

README.rst
doc/_templates/layout.html
doc/installing.rst
doc/memory.rst
doc/parallel.rst

All the changed urls are available by way of https://, and they all already had some form of redirect in place.

Prefer https:// links in the documentation

---

joblib/test/test_dask.py

On my laptop, running the latest version of dask and distributed, with tests that run in a random order for some reason,
- the cleanup fixture (dependency of the loop fixture) would be not found by pytest (see https://github.com/dask/dask/issues/9137),
- tests executed after `test_joblib_warning_inside_dask_daemonic_worker` would either fail or error at teardown because of non-collected subprocess workers from that test.

Stricter Dask tests cleanup

---

.readthedocs.yaml
joblib/_parallel_backends.py

Looking at the code that handle `n_inner_num_threads`, it was a bit circonvoluted.
This PR simply simplify for easier read.

CLN simplify code for easier read

---

CHANGES.rst
azure-pipelines.yml
continuous_integration/run_tests.sh
joblib/_dask.py
joblib/_parallel_backends.py
joblib/_utils.py
joblib/test/test_parallel.py
pyproject.toml

Reasonably simple changes, it seems to be just working as intended. Let's see if the CI agrees.
Are there particular tests to add on top ? the code paths for return_as=generator are the same than for return_as=list so test_dask already tests most of it.

Update dask backend for compatibility with return_as=generator

---

examples/parallel_random_state.py

Hi, 
I found a small imprecision in the parallel random state example [^1], as using iterative seed is not recommended as per [^2]. This PR update the example to the best practice, and add a reference to  the Numpy documentation for the curious reader.
[^1]: https://joblib.readthedocs.io/en/latest/auto_examples/parallel_random_state.html#sphx-glr-auto-examples-parallel-random-state-py
[^2]: https://numpy.org/doc/stable/reference/random/parallel.html#sequence-of-integer-seeds

DOC: Best randomness with Parallel generators

---

joblib/test/test_parallel.py

The distributed pipeline seemed to be less stable after https://github.com/joblib/joblib/pull/1520 , all tests do pass and there is no deadlock but the python interpreter terminates with an error code and outputs a long traceback related to backend termination.
This PR might help fix that, it ensures that when a distributed.Client is opened locally in unit tests, it is also closed cleanly before exiting the test (like it has always been done in https://github.com/joblib/joblib/blob/master/joblib/test/test_dask.py but was overlooked in https://github.com/joblib/joblib/blob/master/joblib/test/test_parallel.py )

FIX Close cleanly distributed Client at the end of unit tests

---

joblib/test/test_parallel.py

Works with Pytest 7.x+
We needed this patch for the Debian package of joblib as we are switching to Pytest 8.0.2+

Add pytest 8.x compatability

---

CHANGES.rst
joblib/parallel.py
joblib/test/test_parallel.py

Based on https://github.com/joblib/joblib/issues/1539

n_jobs parameter in instantiation of Parallel should be an integer

---

CHANGES.rst
continuous_integration/install.sh
joblib/_store_backends.py
joblib/memory.py
joblib/test/test_memory.py
joblib/test/test_memory_async.py

Addresses #889, allowing coroutine functions (available in Python 3.5+) to be decorated with `joblib.memory`. In short, the decorated function's `__call__` and `call_and_shelve` are coroutine functions that when `await`ed return the output or `MemorizedResult`, respectively, that would normally return if the original function was not a coroutine. A small subset of tests were ported from `test_memory` to their asyncio equivalent to verify the expected behavior.
In order to keep the asyncio-specific implementation as small as possible, I had to refactor a large portion of `memory.py` first. It's a separate commit so it can be reviewed and tested independently.

ENH allow caching coroutine functions

---

joblib/test/test_parallel.py

This test shows that the current behavior regarding byteorder consistency in IPC is fine, and will also show that there's no regression in https://github.com/joblib/joblib/pull/1561 .

Add a test that ensure conservation of byte order during IPC

---

doc/parallel.rst

change ``return_as="unordered_generator"`` to ``return_as="generator_unordered"``

[DOC] Typo in docs

---

CHANGES.rst
joblib/memory.py
joblib/test/test_memory.py

Following the reasoning and implementation behind #820, this PR adds a public method to check if a given cached function call is in cache and valid (=meets the cache validation callback function).

Add public method to upfront check if call in cache and valid

---

CHANGES.rst
joblib/_store_backends.py
joblib/memory.py
joblib/test/test_memory.py

Hi,
I have been confused by the argument age_limit for some time now.
Here's the current phrasing:
> age_limit: datetime.timedelta, optional
Maximum age of items to limit the cache to. When reducing the size of the cache, any items last accessed more than the given length of time ago are deleted.
So if your mind focuses on the term "age_limit" it's obvious that to remove a >3 day old item you should use age_limit=timedelta(days=3). But if you focus on the term "timedelta" you can easily think relatively to yourself: 'to remove a >3 days old item, I should pick a threshold date that is 3 days into the passed, so age_limit=timedelta(days=-3)'. The fact that this impossible argument is accepted (no cache elements could be in the future) is to me problematic.
I decided to add an example in …

minor: enforce age_limit>0 and clarify docs

---

joblib/parallel.py

In [a CI run](https://github.com/mne-tools/mne-python/actions/runs/11782225929/job/32816828270?pr=12951#step:17:4834) I just got:
```python
__________________________ test_cross_val_multiscore ___________________________
/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/joblib/parallel.py:1847: in _get_sequential_output
res = func(*args, **kwargs)
mne/parallel.py:127: in run_verbose
return func(*args, **kwargs)
mne/decoding/base.py:495: in _fit_and_score
test_score = _score(estimator, X_test, y_test, scorer)
mne/decoding/base.py:520: in _score
score = scorer(estimator, X_test, y_test)
/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/sklearn/metrics/_scorer.py:288: in __call__
return self._score(partial(_cached_call, None), estimator, X, y_true, …
```

BUG: Avoid division by zero

---

SECURITY.md

Close https://github.com/joblib/joblib/issues/1636.
I copied and pasted the scikit-learn `SECURITY.md` and tweaked a few places.
Not sure about the Tidelift mention, maybe just remove it for joblib? Or do we want to set things up with TideLift for joblib as well? Here is the [TideLift security process](https://support.tidelift.com/hc/en-us/articles/4406287910036-Security-process) for more context.

MNT Add SECURITY.md

---

.github/workflows/test.yml

In the context of the timeout in https://github.com/joblib/joblib/issues/1639, the default timeout is 6 hours. In normal conditions, the longer CI job is the scikit-learn tests one and takes less than 15 minutes, so I used 30 minutes to have some kind of margin.

CI Use 30 minutes timeout for tests

---

.github/workflows/test.yml

Github actions code scanning nudges us towards explicit permissions. Reported in https://github.com/joblib/joblib/security/code-scanning/4.

MNT Use explicit permissions in GHA workflow

---

pyproject.toml

Follow-up of #1628, seen in https://github.com/joblib/joblib/pull/1645/files for example at the bottom:

MNT Avoid codespell warning about file with special encoding

---

.readthedocs-requirements.txt
continuous_integration/run_tests.sh

It started by looking at whether we actually needed pillow for something and then cleaning up a few things that I noticed ...
Let's see what the CI has to say.
Context: I was looking at https://deps.dev/pypi/joblib that claims that joblib has 66 vulnerabilities (bottom right).
I looked at a few of them and they were all coming from Pillow ...

MNT Minor CI clean-up

---

joblib/test/test_parallel.py

Apply a slightly modified version of #1478 
Avoid false positive test failures when some deprecation warning are present in python.
Closes #1478

FIX potential test failures due to deprecation warnings

---

joblib/parallel.py
joblib/test/test_parallel.py

Fixes https://github.com/joblib/joblib/issues/1586
This is an instance of "all the code was covered but didn't test for all the possible combination of parameters". I have added relevant additional parameters to timeout tests.
A note on the proposed fix. Unfortunately the change is not as simple as adding "if timeout is not None then raise TimeoutError" somewhere. The `parallel.py` code is quite hard to browse, one reason might be that it has to deal with ordered and unordered cases with "if/else" blocks with strategies that can be very different at times but it still tries to re-use common logic.
More specifically, some of those differences are:
- **ordered case**: when a batch of task is dispatched, the reference to the task is added to `self._jobs` _before_ the dispatch. This enables …

Fix timeout not working with `return_as=generator_unordered`

---

.git-blame-ignore-revs

This makes the formatter commit to be ignored in `git blame`.
One needs to run
```sh
$ git config blame.ignoreRevsFile .git-blame-ignore-revs
```
to enable the ignore functionality.
cc @tomMoral @lesteve

MNT ignore formatter PR to fix git blame

---

joblib/memory.py
joblib/numpy_pickle.py
joblib/pool.py
joblib/test/test_memory.py
joblib/test/test_numpy_pickle.py

Those have been deprecated for quite a long time and we never removed them ...
- `Memory` `argument_hash` should have been removed in 0.14 released in 2019
- `cache_size` `dump` argument deprecated since 0.10 released in 2016
- `context_id` in `joblib.pool` should have been removed in 0.11 released in 2017

MNT Remove deprecated functions

---

joblib/test/test_parallel.py

Our CI always install it but local testing might fail otherwise.

Make threadpoolctl an optional (test) dependency

---

CHANGES.rst
joblib/hashing.py

Python 3.14 added the obj argument.
This way, the code should work on both 3.13 and 3.14.
Fixes https://github.com/joblib/joblib/issues/1658

Update API and usage of _batch_setitems() to allow more arguments

---

joblib/_memmapping_reducer.py
joblib/test/test_memmapping.py

Fix https://github.com/joblib/joblib/issues/1703
It looks like in #1703 case the base array is 1d (hence both Fortran-contiguous and C-contiguous) and the memmap reducing incorrectly reconstruct the array as Fortran order.

FIX Fix issue in memmap reducing when base array is 1d

---

joblib/test/test_dask.py

Still investigating, because the test is still red at the moment:
>      assert z.count == n_serialization_with_parallel
> E       assert 46 == 43
> E        +  where 46 = <joblib.test.test_dask.CountSerialized object at 0x79f2d0620e90>.count

Check that dask backend serializes same amount of time than native dask.

---

.codecov.yml
.github/workflows/test.yml

This hides the codecov token away behind the gitbub secrets.
Working on it with @lesteve.

CI hide codecov token in secrets settings

---

joblib/memory.py

`asyncio.iscoroutinefunction` is deprecated in Python 3.14 and the warning advises to use `inspect.iscoroutinefunction` instead:
```
DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead
```
I noticed when trying to run the scikit-learn tests with Python 3.14rc2.

MNT Replace asyncio.iscoroutinefunction that is deprecated in Python 3.14
