joblib/joblib

joblib/hashing.py, joblib/test/test_hashing.py
=> Fix hashing of datetime-like numpy arrays

.gitignore, CHANGES.rst, benchmarks/bench_auto_batching.py, joblib/parallel.py, joblib/test/test_parallel.py
This is based on an online evaluation of the batch completion time to dynamically tune the size of the batch of tasks to dispatch at once to a worker.
TODO:
=> [MRG] Automatically group short tasks in batches

appveyor.yml, appveyor/install.ps1
Also updated the install.ps1 script.
=> MAINT reuse pre-installed python on appveyor

CHANGES.rst, doc/parallel.rst, joblib/parallel.py, joblib/test/test_parallel.py
This should make it easier to use parallel calls interleaved in loop as done in scikit-learn/scikit-learn#4873 for instance (ping @arthurmensch).
=> [MRG] New context manager API for joblib.Parallel

joblib/hashing.py
with python 3. Fix #250.
Rather than trying to pickle numpy.dtype objects, which
give rise to multiple problems with hashing, we used its .desr
attribute which is a full description of the dtype.
This allow not to rely on the persistent_id workaround. The reason it
wasn't working in the first place is that because joblib.dumps(dt) is
not stable across python runs, because the order of dt.fields
changes (dict order randomization in python3).
@arthurmensch if you want to have a look.
=> Fix joblib.test.test_hashing.test_dtype random failure

CHANGES.rst, doc/parallel.rst, joblib/parallel.py, joblib/test/test_parallel.py
=> FIX revert back to the fork start method by default

joblib/numpy_pickle.py, joblib/test/test_numpy_pickle.py
For object dtype, we do not try to save the numpy array in an auxiliary file but just do a pickle.dump in the master pickle file.
Added a numpy array with dtype object in test_compressed_pickle_dump_and_load. Also test the code branch where the array size is bigger than the 'cache_size' argument of joblib.dump.
Fix #220.
=> [MRG] fix joblib dump for numpy arrays of dtype object

joblib/hashing.py, joblib/test/test_hashing.py, joblib/testing.py
=> [MRG+1] Do not swallow PicklingError during hash

CHANGES.rst, joblib/parallel.py, joblib/test/test_parallel.py
=> [MRG] Fix Parallel hanging with exhausted iterator

README.rst, doc/installing.rst, doc/parallel_numpy.rst, doc/persistence.rst, joblib/__init__.py
A few fixes about documentation.
=> DOC fixing wording in documentation

joblib/func_inspect.py, joblib/test/test_func_inspect.py, joblib/test/test_memory.py
which is deprecated and raises an Exception with functions that use
signature or keyword-only argument.
Fix #247, fix #182.
=> [MRG+1] Replace inspect.getargspec usages

joblib/_multiprocessing_helpers.py
=> FIX imported but unused + pep8

joblib/pool.py
=> DOC fixing docstrings

.travis.yml, continuous_integration/flake8_diff.sh, continuous_integration/install.sh, continuous_integration/test_script.sh
Similar to what I did in nilearn except that here the flake8 build is not allowed to fail.
=> [MRG] add flake8 linting of diffs in Travis

CHANGES.rst, doc/parallel.rst, joblib/__init__.py, joblib/_compat.py, joblib/_parallel_backends.py, joblib/my_exceptions.py, joblib/parallel.py, joblib/pool.py, joblib/test/test_parallel.py
This is a rebased version of #306 along with some documentation. As we already had +2 (my-self included from the previous PR) I plan to merge this as soon as CI is green.
=> [MRG+2] Refactored Parallel backends

joblib/pool.py
This is a tentative workaround for a weird behavior of Python's atexit reported in #328.
=> FIX TypeError when calling delete_folder via atexit

joblib/_parallel_backends.py, joblib/parallel.py, joblib/test/test_parallel.py
borked the rebase in the old branch.  This one should be cleaner
=> Timeout 2, proper rebase off joblib/master

joblib/test/test_numpy_pickle.py
Adding test data cases related to issue #280.
=> TST: add extra data for testing endianness

joblib/hashing.py, joblib/test/test_hashing.py
=> [MRG] bug when hashing zerod array

joblib/numpy_pickle.py, joblib/test/test_numpy_pickle.py
PR following discussion on #260.
=> [MRG] avoid memory copies when writing chunks of data

joblib/numpy_pickle_utils.py
This should fix #401.
Btw, I have no idea how to test this automatically as prebuilt versions of python standard library come by default with bz2.
=> [MRG+1] make bz2 compression optional

joblib/numpy_pickle_utils.py
=> make lzma compression only supported with python >=3

joblib/numpy_pickle_utils.py, joblib/test/test_numpy_pickle.py
=> [MRG] make BinaryZlibFile seekable

README.rst, setup.py
Install development dependencies with "pip install .[dev]".
=> Dependencies

joblib/parallel.py
Usual caveat about catching an exception, raising the exception and losing some information in the stacktrace.
An example I bumped into when writing a custom parallel backend:
```py
from joblib import Parallel, delayed
from joblib.parallel import ParallelBackendBase, parallel_backend
class Result(object):
def __init__(self, result):
self.result = result
def get(self, timeout=None):
1/0
class MyBackend(ParallelBackendBase):
def apply_async(self, batch, callback):
return Result(batch())
def effective_n_jobs(self, n_jobs):
return n_jobs
def func(i):
return i
with parallel_backend(MyBackend(), n_jobs=2):
Parallel(n_jobs=2)(delayed(func)(i) for i in range(10))
```
On Python 2.7 (on Python 3 the problem is less severe):
master:
```
Traceback (most recent call last):
File "/tmp/test.py", line …
```
=> [MRG] Reraise when the exception is not a TransportableException

doc/memory.rst
Recommend to cache pure functions that you call inside a method.
Add more information on caveats.
Initiated by #431.
=> [MRG] Improve doc about caching methods

joblib/backports.py, joblib/numpy_pickle.py, joblib/pool.py, joblib/test/test_backports.py, joblib/test/test_numpy_pickle.py, joblib/test/test_parallel.py, joblib/test/test_pool.py
Fixes https://github.com/joblib/joblib/issues/451.
ping @ogrisel @aabadie.
=> [MRG] Provide backport for numpy memmap fix when offset is greater than mmap.ALLOCATIONGRANULARITY

CHANGES.rst, joblib/_parallel_backends.py, joblib/parallel.py, joblib/test/test_parallel.py
=> [MRG] Fix speed regression for n_jobs=1

joblib/format_stack.py
Just making sure the CI pass on this one before I merge it.
=> [MRG] MAINT remove dead code and simplify try/except

joblib/memory.py
=> [MRG] COSMIT: fix imported but unused issue

CHANGES.rst, joblib/backports.py, joblib/memory.py, joblib/test/test_backports.py, joblib/test/test_memory.py
Fixes https://github.com/joblib/joblib/issues/490.
=> [MRG] Fix race condition in Memory when persisting output in parallel

appveyor.yml, continuous_integration/appveyor/requirements.txt, continuous_integration/appveyor/test.ps1
Having intermittent problems with errors on AppVeyor that I can not reproduce locally .... :angry:
=> [MRG] Enable codecov on AppVeyor

README.rst
and move the badge to the top.
This is just a cosmit PR, I find the pypi badge quite nice.
=> [MRG] Add pypi badge to Readme

joblib/func_inspect.py, joblib/memory.py, joblib/test/test_func_inspect.py, joblib/test/test_memory.py
=> [MRG] Shorten signature when there is an exception while loading cached results 

benchmarks/bench_pickle.py
Fixes [alert raised by lgtm.com](https://lgtm.com/projects/g/joblib/joblib/snapshot/60218f0eefd2f877571fe87fee72a842dcb4bed6/files/benchmarks/bench_pickle.py#xfa3e8c11238d3078:1)
Very minor.
=> benchmarks: fix broken loop in bench_pickle.py script

joblib/disk.py, joblib/externals/cloudpickle/__init__.py, joblib/externals/cloudpickle/cloudpickle.py, joblib/externals/loky/__init__.py, joblib/externals/loky/backend/queues.py, joblib/externals/loky/backend/utils.py, joblib/externals/loky/process_executor.py
Will merge if CI is green. Those are mostly internal changes / bugfixes and should not impact joblib integration in anyway.
=> MAINT vendor up loky 1.2.0 and cloudpickle 0.4.0

joblib/externals/loky/process_executor.py
Hopefully this should fix random failures on travis such as:  #560.
=> [MRG] Upgrade to loky 1.2.1

joblib/__init__.py
Fixes #566 
With respect, dedicated to the mighty @ogrisel  ;)
=> BF: create a proper temp cache dir in the doctest instead of /tmp/joblib

joblib/test/test_parallel.py
This recently failed randomly on travis.
=> FIX race condition in test_dispatch_multiprocessing

.readthedocs-requirements.txt, continuous_integration/travis/install.sh, doc/conf.py, doc/index.rst, doc/parallel_numpy.rst, examples/README.txt, examples/parallel_memmap.py
Add some general examples using sphinx-gallery.
TODO:
=> [MRG] DOC add sphinx-gallery

.travis.yml, continuous_integration/circle/build_doc.sh, continuous_integration/travis/install.sh
The doc is tested on CircleCI now. Lifted from #592. Will merge when green.
=> [MRG] MAINT remove doc build from Travis.

examples/parallel_random_state.py
This example shows how to use and control the random state in joblib.Parallel
=> DOC Example to illustrate usage of random state in Parallel

README.rst
This PR provides a small cleanup of the README: #623 changes the way the html documentation is built but didn't fully update the README accordingly.
=> README: update notes about how to build the docs

joblib/_memmapping_reducer.py, joblib/_parallel_backends.py, joblib/test/test_memmapping.py, joblib/test/test_parallel.py
=> [MRG] Fix pickle support for ArrayMemmapReducer

continuous_integration/circle/build_doc.sh, examples/memory_basic_usage.py, examples/nested_parallel_memory.py
See https://github.com/joblib/joblib/pull/635#issuecomment-367390365
=> MAINT pin sphinx 1.6.3 while sphinx-gallery / numpydoc get updated

joblib/memory.py, joblib/test/test_memory.py
This PR fixes #638 
Not sure this is the best fix though.
=> FIX: cachedir and location attributes not set in Memory object

.travis.yml, continuous_integration/travis/conftest.py, continuous_integration/travis/copy_joblib.sh, continuous_integration/travis/test_script.sh, joblib/memory.py, joblib/test/test_memory.py
As suggested by @lesteve in https://github.com/joblib/joblib/issues/638#issuecomment-369156666 it might be a good idea to run scikit-learn tests has non-regression tests. Let's try if the following travis setup works as expected.
=> [MRG] run scikit-learn tests on CI

joblib/_parallel_backends.py, joblib/externals/loky/__init__.py, joblib/externals/loky/_base.py, joblib/externals/loky/backend/_win_wait.py, joblib/externals/loky/backend/context.py, joblib/externals/loky/backend/popen_loky_posix.py, joblib/externals/loky/backend/queues.py, joblib/externals/loky/backend/semaphore_tracker.py, joblib/externals/loky/backend/utils.py, joblib/externals/loky/process_executor.py, joblib/externals/loky/reusable_executor.py, joblib/parallel.py
Vendor `loky2.0` in `joblib` and switch from `multiprocessing.cpu_count` to `loky.cpu_count`.
=> Mtn vendor loky 2.0

.travis.yml, joblib/testing.py
Quick PR to fix a random travis failure on overloaded workers.
=> FIX increase default timeout for check_subprocess_call

joblib/memory.py
- Looks like an oversight introduced in #397
=> memory: Fix %{0} -> {0} in str.format

continuous_integration/travis/test_script.sh
=> CI freeze the version of sklearn0.19.1 and scipy1.0.1

continuous_integration/circle/build_doc.sh, doc/conf.py, examples/parallel/README.txt, examples/parallel/distributed_backend_simple.py
A simple dask.distributed example
=> [MRG] Add a dask.distributed example

.readthedocs-requirements.txt
Forgot to add distributed in the readthedocs dependencies.
=> [MRG] Add distributed on readthedocs

joblib/_parallel_backends.py, joblib/parallel.py
This is required to by the distributed backend "auto-scatter" feature.
=> [MRG+1] Introduce Parallel.__call__ backend callbacks

joblib/externals/loky/__init__.py, joblib/externals/loky/backend/context.py, joblib/externals/loky/backend/popen_loky_posix.py, joblib/externals/loky/backend/semaphore_tracker.py, joblib/externals/loky/backend/semlock.py, joblib/externals/loky/backend/spawn.py, joblib/externals/loky/backend/synchronize.py, joblib/externals/loky/backend/utils.py, joblib/externals/loky/process_executor.py, joblib/externals/loky/reusable_executor.py
The new release of loky features the following improvement:
- Recursive termination of child processes
- `initializer` args in the `get_reusable_executor` factory.
- Improved behavior when `max_workers=None`
=> MTN vendor loky2.1.3

joblib/externals/loky/__init__.py, joblib/externals/loky/backend/utils.py, joblib/externals/loky/process_executor.py, joblib/test/test_parallel.py
Vendor `loky2.1.4` which should fixes #707
=> MTN vendor loky2.1.4

joblib/parallel.py, joblib/test/test_parallel.py
=> Better detection for the cloudpickle wrapper

joblib/parallel.py
=> [MRG] BatchedCalls backward compat

joblib/externals/loky/__init__.py, joblib/externals/loky/backend/utils.py, joblib/externals/loky/process_executor.py
Not released yet but I would like to see how the joblib CI likes it first.
=> Loky 2.2.0

joblib/test/test_memory.py, joblib/test/test_store_backends.py
and move relevant tests there.
=> [MRG] MNT create test file for _store_backends module

joblib/_store_backends.py, joblib/memory.py
=> [MRG] MNT remove mutable default value for backend_options parameter

joblib/externals/cloudpickle/__init__.py, joblib/externals/cloudpickle/cloudpickle.py
=> cloudpickle 0.5.5

joblib/_parallel_backends.py, joblib/test/test_parallel.py
=> Fix nesting level bug

joblib/test/test_parallel.py
=> MAINT remove brittle time based assertion in test

.travis.yml, continuous_integration/travis/install.sh, joblib/externals/loky/__init__.py, joblib/externals/loky/_base.py, joblib/externals/loky/backend/compat.py, joblib/externals/loky/backend/context.py, joblib/externals/loky/backend/reduction.py, joblib/externals/loky/process_executor.py, joblib/test/test_format_stack.py, joblib/test/test_memmapping.py, joblib/test/test_parallel.py
Let's see if travis can run the joblib tests with pypy3.
=> Configuration for PyPy on travis

CHANGES.rst, joblib/externals/cloudpickle/__init__.py, joblib/externals/cloudpickle/cloudpickle.py, joblib/externals/loky/__init__.py, joblib/externals/loky/process_executor.py
Fix #776 (spurious debug print).
=> MAINT Loky 2.3.1 and cloudpickle 0.5.6

CHANGES.rst, joblib/_dask.py, joblib/_parallel_backends.py, joblib/externals/loky/process_executor.py, joblib/parallel.py, joblib/test/test_dask.py, joblib/test/test_parallel.py
=> FIX nested backend setting n_jobs=-1

joblib/externals/cloudpickle/__init__.py, joblib/externals/cloudpickle/cloudpickle.py
Among other fixes, this will remove the annoying deprecation warning about the imp module.
=> cloudpickle 0.6.0

doc/parallel.rst, examples/serialization_and_wrappers.py, examples/utils.py, joblib/externals/loky/backend/reduction.py, joblib/externals/loky/process_executor.py
Add explanation on the serialization process in `joblib` and also add an example introducing `set_loky_pickler`, `LOKY_PICKLER` and `wrap_non_picklable_objects`.
=> DOC serialization and processes

doc/memory.rst, examples/parallel_random_state.py
(that I found while reading the doc)
=> [DOC] More typos

joblib/test/test_init.py
Closes #719 
Added test case to test import errors at top level
=> ENH/TEST : Add test case for import errors at top level

joblib/__init__.py
This was originally motivated by fixing 'an' to 'and', but then I thought while I was here I'd make some other suggestions! happy to rephrase/edit as needed.
=> Some minor documentation rephrasing for the joblib front page

CHANGES.rst
Add missing changelog for #893
=> DOC add missing changelog

joblib/test/test_memmapping.py
=> FIX try to make test_weak_array_key_map unlikely to fail at random

.gitignore, CHANGES.rst, conftest.py, joblib/backports.py, joblib/compressor.py
Fix: #965 that introduced a performance regression.
=> Revert pkg resources

joblib/test/test_hashing.py
Update comment in light of investigation happening at #987.
=> More specific test_hashes_stay_the_same xfail

.codecov.yml, azure-pipelines.yml, continuous_integration/run_tests.sh
Add more debug info to Azure Pipelines to understand if the XML coverage report is there.
=> codecov debugging

joblib/externals/cloudpickle/__init__.py, joblib/externals/cloudpickle/cloudpickle.py, joblib/externals/cloudpickle/cloudpickle_fast.py
Supports type annotations on dynamic functions / methods.
=> MAINT Bump cloudpickle to 1.4.1

joblib/externals/loky/__init__.py, joblib/externals/loky/backend/popen_loky_posix.py, joblib/externals/loky/backend/queues.py, joblib/externals/loky/backend/resource_tracker.py, joblib/externals/loky/backend/spawn.py, joblib/externals/loky/process_executor.py, joblib/externals/loky/reusable_executor.py
=> bump vendored loky to v2.7.0

CHANGES.rst, joblib/__init__.py, setup.py
Ping @pierreglaser @lesteve @tomMoral.
Let me know if I forgot anything in the change log.
=> Release 0.15.0

CHANGES.rst, azure-pipelines.yml, continuous_integration/install.sh, joblib/compressor.py, joblib/test/test_numpy_pickle.py
=> Make LZMA optional

joblib/_dask.py, joblib/_multiprocessing_helpers.py, joblib/_parallel_backends.py, joblib/disk.py, joblib/func_inspect.py
@ogrisel 
This is a continuation of #1067
=> Fix exception causes all over the codebase

joblib/externals/cloudpickle/__init__.py, joblib/externals/cloudpickle/cloudpickle.py, joblib/externals/cloudpickle/cloudpickle_fast.py, joblib/externals/cloudpickle/compat.py
=> MAINT cloudpickle 1.5.0

joblib/parallel.py
Added documentation for the ray implementation of joblib backend.
@GaelVaroquaux
=> [docs] Add ray backend in the docs of parallel_backend.

joblib/externals/cloudpickle/__init__.py, joblib/externals/cloudpickle/cloudpickle.py, joblib/externals/cloudpickle/cloudpickle_fast.py, joblib/externals/loky/__init__.py, joblib/externals/loky/backend/context.py, joblib/externals/loky/backend/queues.py, joblib/externals/loky/backend/reduction.py, joblib/externals/loky/process_executor.py, joblib/parallel.py
This should support Python 3.9 and also add support for physical core detection.
=> Vendor latest cloudpickle and loky

joblib/parallel.py
Fixing trivial formatting which makes the doc render wrong.
=> DOC: fix rst formating

joblib/memory.py
=> DOC: Add missing type in Memory

examples/serialization_and_wrappers.py
https://joblib.readthedocs.io/en/latest/auto_examples/serialization_and_wrappers.html
=> Remove unnecessary backquote in example rst

continuous_integration/install.sh
Similar to https://github.com/scikit-learn/scikit-learn/pull/22381.
=> MAINT pin pytest 6

joblib/test/test_memmapping.py
=> Fix test_child_raises_parent_exits_cleanly

azure-pipelines.yml, conftest.py, continuous_integration/install.sh, joblib/backports.py, joblib/compressor.py, joblib/test/test_numpy_pickle.py
Test against more recent versions of Python and numpy on all platforms.
=> Bump up dependency versions on the CI config

doc/parallel.rst, joblib/parallel.py
I was sad when I couldn't click these to get to the API link, might as well add them!
=> DOC: Link to docs

joblib/externals/cloudpickle/__init__.py, joblib/externals/cloudpickle/cloudpickle.py, joblib/externals/cloudpickle/cloudpickle_fast.py
Bump up cloudpickle to the latest version to support CPython 3.11 and CPython `nogil`.
=> cloudpickle 2.1.0

CHANGES.rst, joblib/externals/loky/__init__.py, joblib/externals/loky/backend/synchronize.py, joblib/externals/loky/process_executor.py, joblib/test/test_parallel.py
=> Vendor loky 3.2.0

doc/conftest.py, joblib/test/common.py, joblib/test/test_memmapping.py, joblib/test/test_parallel.py
This should give more information in case of deadlock.
=> MNT Use faulthandler rather than custom autokill logic

doc/memory.rst
Fixes https://github.com/joblib/joblib/issues/1534
=> DOC add gotcha on non-reproducible pickling

CHANGES.rst, joblib/parallel.py
https://pypi.org/project/codespell
=> CHANGES.rst: Fix typos discovered by codespell

joblib/memory.py
Didn't think small change like that warranted an entry in CHANGES.rst, but lmk if that's not the case.
=> CLN fix typo 'picklable'

joblib/hashing.py
Addresses issue: https://github.com/joblib/joblib/issues/1603
=> [Fips] Add usedforsecurity flag for fips compliance

joblib/parallel.py
=> FIX  Sequential backend print_progress()

CITATION.cff
Close #1660. I tested `CITATION.cff` in a test repo and this seems to do the job.
=> MNT Add CITATION.cff

README.rst
The PR suggests to update the installation instruction `python setup.py install` with `pip install -e .`
=> DOC update README with up-to-date installation instruction

.gitignore, README.rst, continuous_integration/install.sh, doc/installing.rst, setup.py
Removes `setup.py` and fixes its mentions.
cc @lesteve
=> MNT remove setup.py and its mentions

README.rst
Adding info on using pre-commit.
=> DOC add info on pre-commit to README

CHANGES.rst, joblib/externals/cloudpickle/__init__.py, joblib/externals/cloudpickle/cloudpickle.py, joblib/externals/cloudpickle/cloudpickle_fast.py, joblib/externals/loky/__init__.py, joblib/externals/loky/backend/context.py, joblib/externals/loky/backend/fork_exec.py, joblib/externals/loky/backend/queues.py, joblib/externals/loky/backend/reduction.py, joblib/externals/loky/backend/resource_tracker.py, joblib/externals/loky/backend/spawn.py, joblib/externals/loky/cloudpickle_wrapper.py, joblib/externals/loky/process_executor.py, joblib/test/test_memory.py, pyproject.toml
This should fix the `os.fork` warning among other things.
Fixes: #1686.
=> Bump vendored loky to 3.5.1 and cloudpickle to 3.1.1

joblib/hashing.py
Follow-up of https://github.com/joblib/joblib/pull/1688
=> MNT Add comment about _batch_setitems signature change in Python 3.14

.github/workflows/test.yml, continuous_integration/install.sh, continuous_integration/run_tests.sh
We can install free-threaded with conda rather than using the deadsnakes PPA.
=> CI Simplify free-threading setup

doc/memory.rst
=> Fix typo in memory.rst

CHANGES.rst, joblib/parallel.py, joblib/test/test_parallel.py
=> FIX default process backend when multiprocessing is disabled
